const DEFAULT_DATA = {
  program: {
    name: "BSc in Computer Science",
    university: "BRAC University",
    requiredCredits: 124,
    version: "v0.1.4.31",
    websiteUrl: "",
    developerName: "SK Reyad Ali",
    githubUrl: "https://github.com/sk-reyad",
    linkedinUrl: "https://www.linkedin.com/in/sk-reyad/",
  },
  departments: [
    {
      id: "CSE",
      name: "Computer Science and Engineering",
      color: "blue",
    },
    {
      id: "MNS",
      name: "Mathematics and Natural Sciences",
      color: "teal",
    },
    {
      id: "BIL",
      name: "BRAC Institute of Languages",
      color: "amber",
    },
    {
      id: "BBS",
      name: "BRAC Business School",
      color: "purple",
    },
    {
      id: "GED",
      name: "General Education",
      color: "slate",
    },
    {
      id: "OTH",
      name: "Other / Custom",
      color: "gray",
    },
  ],
  gradeScale: [
    {
      grade: "A+",
      point: 4,
      range: "97 - 100",
    },
    {
      grade: "A",
      point: 4,
      range: "90 - <97",
    },
    {
      grade: "A-",
      point: 3.7,
      range: "85 - <90",
    },
    {
      grade: "B+",
      point: 3.3,
      range: "80 - <85",
    },
    {
      grade: "B",
      point: 3,
      range: "75 - <80",
    },
    {
      grade: "B-",
      point: 2.7,
      range: "70 - <75",
    },
    {
      grade: "C+",
      point: 2.3,
      range: "65 - <70",
    },
    {
      grade: "C",
      point: 2,
      range: "60 - <65",
    },
    {
      grade: "C-",
      point: 1.7,
      range: "57 - <60",
    },
    {
      grade: "D+",
      point: 1.3,
      range: "55 - <57",
    },
    {
      grade: "D",
      point: 1,
      range: "52 - <55",
    },
    {
      grade: "D-",
      point: 0.7,
      range: "50 - <52",
    },
    {
      grade: "F",
      point: 0,
      range: "<50",
    },
    {
      grade: "P",
      point: null,
      range: "Pass",
    },
    {
      grade: "I",
      point: null,
      range: "Incomplete",
    },
    {
      grade: "W",
      point: null,
      range: "Withdrawal",
    },
  ],
  categories: [
    {
      id: "program-core",
      label: "Program Core",
    },
    {
      id: "school-core",
      label: "School Core",
    },
    {
      id: "program-elective",
      label: "Program Elective",
    },
    {
      id: "gened",
      label: "GenEd",
    },
    {
      id: "non-credit",
      label: "Non-credit",
    },
    {
      id: "cod-slot",
      label: "COD Slot",
    },
    {
      id: "elective-slot",
      label: "Elective Slot",
    },
    {
      id: "thesis-project",
      label: "Thesis / Project / Internship",
    },
    {
      id: "custom",
      label: "Custom",
    },
  ],
  courses: [
    {
      code: "CSE110",
      title: "Programming Language I",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 1,
      roadmapOrder: 1,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT110",
      title: "MATH I: Differential Calculus and Co-ordinate Geometry",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd Math",
      isRoadmapSlot: false,
    },
    {
      code: "ENG101",
      title: "English Fundamentals",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd English",
      isRoadmapSlot: false,
    },
    {
      code: "PHY111",
      title: "Principles of Physics I",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CSE111",
      title: "Programming Language II",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 2,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE110"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE230",
      title: "Discrete Mathematics",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 2,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "STA201",
      title: "Elements of Statistics and Probability",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 2,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: ["MAT110"],
      sourceNote: "Degree Plan GenEd Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "PHY112",
      title: "Principles of Physics II",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 2,
      roadmapOrder: 4,
      hardPrerequisites: ["PHY111"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "BNG103",
      title: "Bangla Language and Literature",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 1,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan Stream 3",
      isRoadmapSlot: false,
    },
    {
      code: "EMB101",
      title: "Emergence of Bangladesh",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan Social Sciences option",
      isRoadmapSlot: false,
    },
    {
      code: "ENG102",
      title: "English Composition I",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 3,
      hardPrerequisites: ["ENG101"],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd English",
      isRoadmapSlot: false,
    },
    {
      code: "HUM103",
      title: "Ethics and Culture",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan Global Thinking / Humanities",
      isRoadmapSlot: false,
    },
    {
      code: "CSE220",
      title: "Data Structures",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 4,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE111"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT120",
      title: "MATH II: Integral Calculus and Differential Equations",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 4,
      roadmapOrder: 2,
      hardPrerequisites: ["MAT110"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-1",
      title: "Elective 1",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 4,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-1",
      title: "COD 1",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 4,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE221",
      title: "Algorithms",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 5,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE220"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT216",
      title: "MATH IV: Linear Algebra and Fourier Analysis",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 5,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-2",
      title: "Elective 2",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 5,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-2",
      title: "COD 2",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 5,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE321",
      title: "Operating Systems",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: ["CSE340"],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE330",
      title: "Numerical Methods",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 2,
      hardPrerequisites: ["MAT216"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE260",
      title: "Digital Logic Design",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS core; prerequisite editable by user",
      isRoadmapSlot: false,
    },
    {
      code: "COD-3",
      title: "COD 3",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 6,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE370",
      title: "Database Systems",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 7,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT215",
      title: "MATH III: Complex Variables and Laplace Transformations",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 7,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "CSE340",
      title: "Computer Architecture",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 7,
      roadmapOrder: 3,
      hardPrerequisites: ["CSE260"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-3",
      title: "Elective 3",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 7,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE422",
      title: "Artificial Intelligence",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 8,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-4",
      title: "Elective 4",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 8,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "ELECTIVE-5",
      title: "Elective 5",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 8,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-4",
      title: "COD 4",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 8,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE331",
      title: "Automata and Computability",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 9,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-6",
      title: "Elective 6",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 9,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE-ELECTIVE",
      title: "CSE Elective",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 9,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Required CSE elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-5",
      title: "COD 5",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 9,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE420",
      title: "Compiler Design",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE321", "CSE331", "CSE340"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE421",
      title: "Computer Networks",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: ["CSE320"],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE423",
      title: "Computer Graphics",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 3,
      hardPrerequisites: ["MAT216"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "COD-6",
      title: "COD 6",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 10,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE470",
      title: "Software Engineering",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 11,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE370"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE400",
      title: "Final-Year Project / Internship / Thesis",
      credits: 4,
      department: "CSE",
      category: "thesis-project",
      roadmapLevel: 11,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "BIO101",
      title: "Biology",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CHE101",
      title: "Chemistry",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CSE250",
      title: "Circuits and Electronics",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: ["PHY112"],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE251",
      title: "Electronic Devices and Circuits",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE250"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE310",
      title: "Object Oriented Programming",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE111"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE320",
      title: "Data Communication",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE341",
      title: "Microprocessor",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: ["CSE340"],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE342",
      title: "Computer Systems Engineering",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE350",
      title: "Digital Electronics and Pulse Techniques",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE251"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE360",
      title: "Computer Interface",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE341"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE390",
      title: "Technical Communication",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE391",
      title: "Programming for the Internet",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE392",
      title: "Signals and Systems",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE410",
      title: "Advanced Programming in UNIX",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE419",
      title: "Programming Languages",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE424",
      title: "Pattern Recognition",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE425",
      title: "Neural Networks",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE426",
      title: "Basic Graph Theory",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE427",
      title: "Machine Learning",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE428",
      title: "Image Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE429",
      title: "Basic Multimedia Theory",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE430",
      title: "Digital Signal Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE431",
      title: "Natural Language Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE432",
      title: "Speech Recognition and Synthesis",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE460",
      title: "VLSI Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE260"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE461",
      title: "Digital System Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE260", "CSE341", "CSE360"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE462",
      title: "Fault Tolerant Systems",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE471",
      title: "System Analysis and Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE370"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE472",
      title: "Human Computer Interface",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE473",
      title: "Decision Support System",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE474",
      title: "Simulation and Modeling",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE490",
      title: "Special Topics / WAN Routing and Technologies",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE491",
      title: "Independent Study",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "DEV101",
      title: "Bangladesh Studies / Development Studies",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd option; not placed on roadmap by default",
      isRoadmapSlot: false,
    },
    {
      code: "ENG091",
      title: "Foundation Course in English",
      credits: 0,
      department: "BIL",
      category: "non-credit",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan / user backup",
      isRoadmapSlot: false,
    },
    {
      code: "ENG103",
      title: "Advanced Writing Skills and Presentation",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["ENG102"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan optional for ENG102 freshers",
      isRoadmapSlot: false,
    },
    {
      code: "ENV103",
      title: "Introduction to Environmental Science",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
  ],
  defaultFaculties: [
    {
      department: "MNS",
      id: "fac-1781436937825-8bbac00d50f25",
      name: "Sanjeeda Nazneen",
      email: "sanjeeda@bracu.ac.bd",
      initial: "SAN",
    },
    {
      department: "CSE",
      id: "fac-1781436964511-a4e5c8ec351578",
      name: "Ahmed Mahir Ruhan",
      email: "ahmed.ruhan@bracu.ac.bd",
      initial: "ADU",
    },
    {
      department: "BIL",
      id: "fac-1781437189834-f0539fecfed908",
      name: "Tanjeela Osmani",
      email: "tanjeela.osmani@bracu.ac.bd",
      initial: "TAO",
    },
    {
      department: "MNS",
      id: "fac-1781437261874-346c0f72503f5",
      name: "Tanveer Islam",
      email: "ext.priyanka.chak@bracu.ac.bd",
      initial: "TNVR",
    },
    {
      department: "CSE",
      id: "fac-1781437570512-e64737646179f",
      name: "Prothito Shovon Majumder",
      email: "prothito.shovon@bracu.ac.bd",
      initial: "PSMD",
    },
    {
      department: "BIL",
      id: "fac-1781437644904-c75b0063affff8",
      name: "Md. Julhas Uddin",
      email: "julhas@bracu.ac.bd",
      initial: "JUL",
    },
    {
      department: "CSE",
      id: "fac-1783432205256-e1f6702fc65f",
      name: "Sadiul Arefin Rafi",
      email: "ext.sadiul.rafi@bracu.ac.bd",
      initial: "SLAR",
    },
    {
      department: "MNS",
      id: "fac-1783432339836-bbcfd92172be8",
      name: "Farzana Zaman",
      email: "farzana25zaman@gmail.com",
      initial: "FZZ",
    },
    {
      department: "GED",
      id: "fac-1783432481590-a1a71cfbecaac",
      name: "Chaitee Chakraborty",
      email: "chaitee.chakraborty@bracu.ac.bd",
      initial: "MCC",
    },
    {
      department: "GED",
      id: "fac-1783432546878-11dd065e7ed6b8",
      name: "Sawban Ibn Farid",
      email: "sawban.farid@bracu.ac.bd",
      initial: "SWBN",
    },
    {
      department: "GED",
      id: "fac-1783432675055-15eaa50eab3a68",
      name: "Priyanka Chak",
      email: "",
      initial: "PRCK",
    },
    {
      department: "BIL",
      id: "fac-1783432703649-d66da0546e5b48",
      name: "Jannatul Ferdous",
      email: "jannatul.ferdous@bracu.ac.bd",
      initial: "JNF",
    },
    {
      department: "CSE",
      id: "fac-1783432813473-cf6406aea417f8",
      name: "Dewan Ziaul Karim",
      email: "ziaul.karim@bracu.ac.bd",
      initial: "DZK",
    },
    {
      department: "MNS",
      id: "fac-1783432901276-29aa69f2fe53a",
      name: "Rifat Hasan Rubel",
      email: "ext.rifat.hasan@bracu.ac.bd",
      initial: "RHR",
    },
    {
      department: "MNS",
      id: "fac-1783432976002-b18d405ef4f708",
      name: "Dr. Md Tanjib Atique Khan",
      email: "ext.tanjib.atique@bracu.ac.bd",
      initial: "TJB",
    },
    {
      department: "CSE",
      id: "fac-1783433107824-7a32be6683d608",
      name: "Tanjim Reza",
      email: "ext.tanjim.reza@bracu.ac.bd",
      initial: "TRZA",
    },
    {
      department: "CSE",
      id: "fac-1783433205156-e1a1c4255634d8",
      name: "Asif Shahriar",
      email: "asif.shahriar@bracu.ac.bd",
      initial: "SHAH",
    },
    {
      department: "MNS",
      id: "fac-1783433337163-9b0bda7bc8156",
      name: "Dulali Iqbal",
      email: "ext.dulali.iqbal@bracu.ac.bd",
      initial: "DLI",
    },
  ],
  defaultProfile: {
    name: "SK Reyad Ali",
    studentId: "24210009",
    email: "sk.reyad.ali@g.bracu.ac.bd",
    program: "BSc in Computer Science",
    university: "BRAC University",
    batch: "",
    startingSemester: "Fall 2024",
    profilePhoto: "",
  },
  defaultSemesters: [
    {
      id: "sem-1781436868699-4f7fb111a8abd",
      number: 1,
      name: "Fall 2024",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437018675-0fe809760a188",
          code: "MAT110",
          status: "completed",
          grade: "A",
          gradePoint: 4,
          facultyId: "fac-1781436937825-8bbac00d50f25",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:36:58.675Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437206372-1d469a44fab4b",
          code: "ENG091",
          status: "completed",
          grade: "P",
          gradePoint: null,
          facultyId: "fac-1781437189834-f0539fecfed908",
          creditsOverride: 0,
          createdAt: "2026-06-14T11:40:06.372Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437283293-c8f99a3357398",
          code: "PHY111",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1781437261874-346c0f72503f5",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:41:23.293Z",
        },
      ],
    },
    {
      id: "sem-1781437466439-4b6742f0fe34e8",
      number: 2,
      name: "Spring 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437513933-abcecc1a4f17d",
          code: "CSE110",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1781436964511-a4e5c8ec351578",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:45:13.933Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437587085-1d4ac4a5594f5",
          code: "CSE230",
          status: "completed",
          grade: "B-",
          gradePoint: 2.7,
          facultyId: "fac-1781437570512-e64737646179f",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:46:27.085Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437652989-f964691e032c7",
          code: "ENG101",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1781437644904-c75b0063affff8",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:47:32.989Z",
        },
      ],
    },
    {
      id: "sem-1783432111862-4741c1f477c9f",
      number: 3,
      name: "Summer 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432144263-5ff1ee67c4619",
          code: "CSE111",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1781436964511-a4e5c8ec351578",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:49:04.263Z",
        },
        {
          repeatType: "RP",
          countsInCGPA: true,
          id: "attempt-1783432217927-8733dc36e3fff8",
          code: "CSE230",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432205256-e1f6702fc65f",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:50:17.927Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432352261-20aba5e06d204",
          code: "STA201",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432339836-bbcfd92172be8",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:52:32.261Z",
        },
      ],
    },
    {
      id: "sem-1783432409611-d4050ac43f4b8",
      number: 4,
      name: "Fall 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432503134-33cba58df6084",
          code: "BNG103",
          status: "completed",
          grade: "A",
          gradePoint: 4,
          facultyId: "fac-1783432481590-a1a71cfbecaac",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:55:03.134Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432721683-69d89d03ba943",
          code: "EMB101",
          status: "completed",
          grade: "A+",
          gradePoint: 4,
          facultyId: "fac-1783432546878-11dd065e7ed6b8",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:58:41.683Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432738133-beed8bf2d762f",
          code: "ENG102",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432703649-d66da0546e5b48",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:58:58.133Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432751451-d79691b9b5ff18",
          code: "HUM103",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1783432675055-15eaa50eab3a68",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:59:11.451Z",
        },
      ],
    },
    {
      id: "sem-1783432764662-8010ec1295f3d8",
      number: 5,
      name: "Spring 2026",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432993538-8c990b15c21a78",
          code: "CSE260",
          status: "completed",
          grade: "B-",
          gradePoint: 2.7,
          facultyId: "fac-1783432813473-cf6406aea417f8",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:13.538Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783433007013-8ad82ae9d0f4f",
          code: "MAT120",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432901276-29aa69f2fe53a",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:27.013Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783433016884-8b0b40dd687888",
          code: "PHY112",
          status: "completed",
          grade: "D+",
          gradePoint: 1.3,
          facultyId: "fac-1783432976002-b18d405ef4f708",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:36.884Z",
        },
      ],
    },
    {
      id: "sem-1783433071283-772cfc3eadfb18",
      number: 6,
      name: "Summer 2026",
      courses: [
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433361358-da7041b513eb9",
          code: "CSE220",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433107824-7a32be6683d608",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:21.358Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433388194-7fd4faa8798358",
          code: "CSE320",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433205156-e1a1c4255634d8",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:48.194Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433399692-c9aa5bfac80e38",
          code: "MAT216",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433337163-9b0bda7bc8156",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:59.692Z",
        },
      ],
    },
    {
      id: "sem-1783433539523-13b6d50a9c0e6",
      number: 7,
      name: "Fall 2026",
      courses: [
        {
          repeatType: "RP",
          countsInCGPA: false,
          id: "attempt-1783433553594-464dc84d91a9f",
          code: "CSE260",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:33.594Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433561259-af37fb6c004c3",
          code: "CSE221",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:41.259Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433571034-03a9bab0eb853",
          code: "MAT215",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:51.034Z",
        },
      ],
    },
  ],
};

function resolveReportWebsiteUrl(configuredUrl, currentHref) {
  const configured = String(configuredUrl || "").trim();
  if (configured) return configured;

  try {
    const current = new URL(String(currentHref || ""));
    if (current.protocol === "http:" || current.protocol === "https:") {
      return `${current.origin}${current.pathname}`;
    }
  } catch {}

  return "this website";
}

if (typeof globalThis !== "undefined") {
  globalThis.DEFAULT_DATA = DEFAULT_DATA;
  globalThis.resolveReportWebsiteUrl = resolveReportWebsiteUrl;
}

if (typeof module === "object" && module.exports) {
  module.exports = { DEFAULT_DATA, resolveReportWebsiteUrl };
}
