const DEFAULT_DATA = {
  program: {
    name: "BSc in Computer Science",
    university: "BRAC University",
    requiredCredits: 124,
    version: "v0.9.0-beta.1",
    websiteUrl: "",
    developerName: "SK Reyad Ali",
    githubUrl: "https://github.com/sk-reyad",
    linkedinUrl: "https://www.linkedin.com/in/sk-reyad/",
  },
  facultyCatalogVersion: 1,
  departments: [
    {
      id: "CSE",
      name: "Computer Science and Engineering",
      color: "blue",
    },
    {
      id: "MNS",
      name: "Mathematics and Natural Sciences",
      color: "teal",
    },
    {
      id: "BIL",
      name: "BRAC Institute of Languages",
      color: "amber",
    },
    {
      id: "BBS",
      name: "BRAC Business School",
      color: "purple",
    },
    {
      id: "GED",
      name: "General Education",
      color: "slate",
    },
    {
      id: "OTH",
      name: "Other / Custom",
      color: "gray",
    },
  ],
  gradeScale: [
    {
      grade: "A+",
      point: 4,
      range: "97 - 100",
    },
    {
      grade: "A",
      point: 4,
      range: "90 - <97",
    },
    {
      grade: "A-",
      point: 3.7,
      range: "85 - <90",
    },
    {
      grade: "B+",
      point: 3.3,
      range: "80 - <85",
    },
    {
      grade: "B",
      point: 3,
      range: "75 - <80",
    },
    {
      grade: "B-",
      point: 2.7,
      range: "70 - <75",
    },
    {
      grade: "C+",
      point: 2.3,
      range: "65 - <70",
    },
    {
      grade: "C",
      point: 2,
      range: "60 - <65",
    },
    {
      grade: "C-",
      point: 1.7,
      range: "57 - <60",
    },
    {
      grade: "D+",
      point: 1.3,
      range: "55 - <57",
    },
    {
      grade: "D",
      point: 1,
      range: "52 - <55",
    },
    {
      grade: "D-",
      point: 0.7,
      range: "50 - <52",
    },
    {
      grade: "F",
      point: 0,
      range: "<50",
    },
    {
      grade: "P",
      point: null,
      range: "Pass",
    },
    {
      grade: "I",
      point: null,
      range: "Incomplete",
    },
    {
      grade: "W",
      point: null,
      range: "Withdrawal",
    },
  ],
  categories: [
    {
      id: "program-core",
      label: "Program Core",
    },
    {
      id: "school-core",
      label: "School Core",
    },
    {
      id: "program-elective",
      label: "Program Elective",
    },
    {
      id: "gened",
      label: "GenEd",
    },
    {
      id: "non-credit",
      label: "Non-credit",
    },
    {
      id: "cod-slot",
      label: "COD Slot",
    },
    {
      id: "elective-slot",
      label: "Elective Slot",
    },
    {
      id: "thesis-project",
      label: "Thesis / Project / Internship",
    },
    {
      id: "custom",
      label: "Custom",
    },
  ],
  courses: [
    {
      code: "CSE110",
      title: "Programming Language I",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 1,
      roadmapOrder: 1,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT110",
      title: "MATH I: Differential Calculus and Co-ordinate Geometry",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd Math",
      isRoadmapSlot: false,
    },
    {
      code: "ENG101",
      title: "English Fundamentals",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd English",
      isRoadmapSlot: false,
    },
    {
      code: "PHY111",
      title: "Principles of Physics I",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 1,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CSE111",
      title: "Programming Language II",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 2,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE110"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE230",
      title: "Discrete Mathematics",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 2,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "STA201",
      title: "Elements of Statistics and Probability",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: 2,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: ["MAT110"],
      sourceNote: "Degree Plan GenEd Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "PHY112",
      title: "Principles of Physics II",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 2,
      roadmapOrder: 4,
      hardPrerequisites: ["PHY111"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "BNG103",
      title: "Bangla Language and Literature",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 1,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan Stream 3",
      isRoadmapSlot: false,
    },
    {
      code: "EMB101",
      title: "Emergence of Bangladesh",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan Social Sciences option",
      isRoadmapSlot: false,
    },
    {
      code: "ENG102",
      title: "English Composition I",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 3,
      hardPrerequisites: ["ENG101"],
      softPrerequisites: [],
      sourceNote: "Degree Plan GenEd English",
      isRoadmapSlot: false,
    },
    {
      code: "HUM103",
      title: "Ethics and Culture",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: 3,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Degree Plan Global Thinking / Humanities",
      isRoadmapSlot: false,
    },
    {
      code: "CSE220",
      title: "Data Structures",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 4,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE111"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT120",
      title: "MATH II: Integral Calculus and Differential Equations",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 4,
      roadmapOrder: 2,
      hardPrerequisites: ["MAT110"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-1",
      title: "Elective 1",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 4,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-1",
      title: "COD 1",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 4,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE221",
      title: "Algorithms",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 5,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE220"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT216",
      title: "MATH IV: Linear Algebra and Fourier Analysis",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 5,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-2",
      title: "Elective 2",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 5,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-2",
      title: "COD 2",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 5,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE321",
      title: "Operating Systems",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: ["CSE340"],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE330",
      title: "Numerical Methods",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 2,
      hardPrerequisites: ["MAT216"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE260",
      title: "Digital Logic Design",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 6,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS core; prerequisite editable by user",
      isRoadmapSlot: false,
    },
    {
      code: "COD-3",
      title: "COD 3",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 6,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE370",
      title: "Database Systems",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 7,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "MAT215",
      title: "MATH III: Complex Variables and Laplace Transformations",
      credits: 3,
      department: "MNS",
      category: "school-core",
      roadmapLevel: 7,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan School Core",
      isRoadmapSlot: false,
    },
    {
      code: "CSE340",
      title: "Computer Architecture",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 7,
      roadmapOrder: 3,
      hardPrerequisites: ["CSE260"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-3",
      title: "Elective 3",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 7,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE422",
      title: "Artificial Intelligence",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 8,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-4",
      title: "Elective 4",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 8,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "ELECTIVE-5",
      title: "Elective 5",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 8,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-4",
      title: "COD 4",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 8,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE331",
      title: "Automata and Computability",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 9,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE221"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "ELECTIVE-6",
      title: "Elective 6",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 9,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Program elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE-ELECTIVE",
      title: "CSE Elective",
      credits: 3,
      department: "OTH",
      category: "elective-slot",
      roadmapLevel: 9,
      roadmapOrder: 3,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Required CSE elective slot",
      isRoadmapSlot: true,
    },
    {
      code: "COD-5",
      title: "COD 5",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 9,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE420",
      title: "Compiler Design",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE321", "CSE331", "CSE340"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE421",
      title: "Computer Networks",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: ["CSE320"],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE423",
      title: "Computer Graphics",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 10,
      roadmapOrder: 3,
      hardPrerequisites: ["MAT216"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "COD-6",
      title: "COD 6",
      credits: 3,
      department: "OTH",
      category: "cod-slot",
      roadmapLevel: 10,
      roadmapOrder: 4,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Course outside department / GenEd slot",
      isRoadmapSlot: true,
    },
    {
      code: "CSE470",
      title: "Software Engineering",
      credits: 3,
      department: "CSE",
      category: "program-core",
      roadmapLevel: 11,
      roadmapOrder: 1,
      hardPrerequisites: ["CSE370"],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "CSE400",
      title: "Final-Year Project / Internship / Thesis",
      credits: 4,
      department: "CSE",
      category: "thesis-project",
      roadmapLevel: 11,
      roadmapOrder: 2,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program core / Degree Plan",
      isRoadmapSlot: false,
    },
    {
      code: "BIO101",
      title: "Biology",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CHE101",
      title: "Chemistry",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
    {
      code: "CSE250",
      title: "Circuits and Electronics",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: ["PHY112"],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE251",
      title: "Electronic Devices and Circuits",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE250"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE310",
      title: "Object Oriented Programming",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE111"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE320",
      title: "Data Communication",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE341",
      title: "Microprocessor",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: ["CSE340"],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE342",
      title: "Computer Systems Engineering",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE350",
      title: "Digital Electronics and Pulse Techniques",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE251"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE360",
      title: "Computer Interface",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE341"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE390",
      title: "Technical Communication",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE391",
      title: "Programming for the Internet",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE392",
      title: "Signals and Systems",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE410",
      title: "Advanced Programming in UNIX",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE419",
      title: "Programming Languages",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE424",
      title: "Pattern Recognition",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE425",
      title: "Neural Networks",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE426",
      title: "Basic Graph Theory",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE427",
      title: "Machine Learning",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE428",
      title: "Image Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE429",
      title: "Basic Multimedia Theory",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE430",
      title: "Digital Signal Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE431",
      title: "Natural Language Processing",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE432",
      title: "Speech Recognition and Synthesis",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE460",
      title: "VLSI Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE260"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE461",
      title: "Digital System Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE260", "CSE341", "CSE360"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE462",
      title: "Fault Tolerant Systems",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE471",
      title: "System Analysis and Design",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["CSE370"],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE472",
      title: "Human Computer Interface",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE473",
      title: "Decision Support System",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE474",
      title: "Simulation and Modeling",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE490",
      title: "Special Topics / WAN Routing and Technologies",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "CSE491",
      title: "Independent Study",
      credits: 3,
      department: "CSE",
      category: "program-elective",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Official CS program elective",
      isRoadmapSlot: false,
    },
    {
      code: "DEV101",
      title: "Bangladesh Studies / Development Studies",
      credits: 3,
      department: "GED",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd option; not placed on roadmap by default",
      isRoadmapSlot: false,
    },
    {
      code: "ENG091",
      title: "Foundation Course in English",
      credits: 0,
      department: "BIL",
      category: "non-credit",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "Updated degree plan / user backup",
      isRoadmapSlot: false,
    },
    {
      code: "ENG103",
      title: "Advanced Writing Skills and Presentation",
      credits: 3,
      department: "BIL",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: ["ENG102"],
      softPrerequisites: [],
      sourceNote: "Updated degree plan optional for ENG102 freshers",
      isRoadmapSlot: false,
    },
    {
      code: "ENV103",
      title: "Introduction to Environmental Science",
      credits: 3,
      department: "MNS",
      category: "gened",
      roadmapLevel: null,
      roadmapOrder: null,
      hardPrerequisites: [],
      softPrerequisites: [],
      sourceNote: "GenEd optional Life & Physical Sciences",
      isRoadmapSlot: false,
    },
  ],
  defaultFaculties: [
    {
      department: "MNS",
      id: "fac-1781436937825-8bbac00d50f25",
      name: "Sanjeeda Nazneen",
      email: "sanjeeda@bracu.ac.bd",
      initial: "SAN",
    },
    {
      department: "CSE",
      id: "fac-1781436964511-a4e5c8ec351578",
      name: "Ahmed Mahir Ruhan",
      email: "ahmed.ruhan@bracu.ac.bd",
      initial: "ADU",
    },
    {
      department: "BIL",
      id: "fac-1781437189834-f0539fecfed908",
      name: "Tanjeela Osmani",
      email: "tanjeela.osmani@bracu.ac.bd",
      initial: "TAO",
    },
    {
      department: "MNS",
      id: "fac-1781437261874-346c0f72503f5",
      name: "Tanveer Islam",
      email: "ext.priyanka.chak@bracu.ac.bd",
      initial: "TNVR",
    },
    {
      department: "CSE",
      id: "fac-1781437570512-e64737646179f",
      name: "Prothito Shovon Majumder",
      email: "prothito.shovon@bracu.ac.bd",
      initial: "PSMD",
    },
    {
      department: "BIL",
      id: "fac-1781437644904-c75b0063affff8",
      name: "Md. Julhas Uddin",
      email: "julhas@bracu.ac.bd",
      initial: "JUL",
    },
    {
      department: "CSE",
      id: "fac-1783432205256-e1f6702fc65f",
      name: "Sadiul Arefin Rafi",
      email: "ext.sadiul.rafi@bracu.ac.bd",
      initial: "SLAR",
    },
    {
      department: "MNS",
      id: "fac-1783432339836-bbcfd92172be8",
      name: "Farzana Zaman",
      email: "farzana25zaman@gmail.com",
      initial: "FZZ",
    },
    {
      department: "GED",
      id: "fac-1783432481590-a1a71cfbecaac",
      name: "Chaitee Chakraborty",
      email: "chaitee.chakraborty@bracu.ac.bd",
      initial: "MCC",
    },
    {
      department: "GED",
      id: "fac-1783432546878-11dd065e7ed6b8",
      name: "Sawban Ibn Farid",
      email: "sawban.farid@bracu.ac.bd",
      initial: "SWBN",
    },
    {
      department: "GED",
      id: "fac-1783432675055-15eaa50eab3a68",
      name: "Priyanka Chak",
      email: "",
      initial: "PRCK",
    },
    {
      department: "BIL",
      id: "fac-1783432703649-d66da0546e5b48",
      name: "Jannatul Ferdous",
      email: "jannatul.ferdous@bracu.ac.bd",
      initial: "JNF",
    },
    {
      department: "CSE",
      id: "fac-1783432813473-cf6406aea417f8",
      name: "Dewan Ziaul Karim",
      email: "ziaul.karim@bracu.ac.bd",
      initial: "DZK",
    },
    {
      department: "MNS",
      id: "fac-1783432901276-29aa69f2fe53a",
      name: "Rifat Hasan Rubel",
      email: "ext.rifat.hasan@bracu.ac.bd",
      initial: "RHR",
    },
    {
      department: "MNS",
      id: "fac-1783432976002-b18d405ef4f708",
      name: "Dr. Md Tanjib Atique Khan",
      email: "ext.tanjib.atique@bracu.ac.bd",
      initial: "TJB",
    },
    {
      department: "CSE",
      id: "fac-1783433107824-7a32be6683d608",
      name: "Tanjim Reza",
      email: "ext.tanjim.reza@bracu.ac.bd",
      initial: "TRZA",
    },
    {
      department: "CSE",
      id: "fac-1783433205156-e1a1c4255634d8",
      name: "Asif Shahriar",
      email: "asif.shahriar@bracu.ac.bd",
      initial: "SHAH",
    },
    {
      department: "MNS",
      id: "fac-1783433337163-9b0bda7bc8156",
      name: "Dulali Iqbal",
      email: "ext.dulali.iqbal@bracu.ac.bd",
      initial: "DLI",
    },
    {
      department: "CSE",
      id: "fac-cse-aar",
      name: "Mr. Annajiat Alim Rasel",
      email: "annajiat@bracu.ac.bd",
      initial: "AAR",
    },
    {
      department: "CSE",
      id: "fac-cse-ach",
      name: "Dr. Amitabha Chakrabarty",
      email: "amitabha@bracu.ac.bd",
      initial: "ACH",
    },
    {
      department: "CSE",
      id: "fac-cse-afq",
      name: "Mohammed Ashfaqul Haque",
      email: "ashfaqul.haque@bracu.ac.bd",
      initial: "AFQ",
    },
    {
      department: "CSE",
      id: "fac-cse-aib",
      name: "Mr. Md. Abu Ibrahim",
      email: "abu.ibrahim@bracu.ac.bd",
      initial: "AIB",
    },
    {
      department: "CSE",
      id: "fac-cse-aja",
      name: "Mr. Abid Jahan Apon",
      email: "abid.jahan@bracu.ac.bd",
      initial: "AJA",
    },
    {
      department: "CSE",
      id: "fac-cse-akj",
      name: "Akib Anjum",
      email: "anjum.akib@bracu.ac.bd",
      initial: "AKJ",
    },
    {
      department: "CSE",
      id: "fac-cse-aktd",
      name: "Md. Akhtaruzaman Adnan",
      email: "akhtaruzzaman.adnan@bracu.ac.bd",
      initial: "AKTD",
    },
    {
      department: "CSE",
      id: "fac-cse-alb",
      name: "Anindita Labonno",
      email: "anindita.labonno@bracu.ac.bd",
      initial: "ALB",
    },
    {
      department: "CSE",
      id: "fac-cse-amk",
      name: "Dr. Abu Mohammad Khan",
      email: "abu.khan@bracu.ac.bd",
      initial: "AMK",
    },
    {
      department: "CSE",
      id: "fac-cse-ankh",
      name: "Anika Ahmed",
      email: "anika.ahmed@bracu.ac.bd",
      initial: "ANKH",
    },
    {
      department: "CSE",
      id: "fac-cse-anwe",
      name: "Abdullah Nayem Wasi Emran",
      email: "abdullah.nayem@bracu.ac.bd",
      initial: "ANWE",
    },
    {
      department: "CSE",
      id: "fac-cse-aqt",
      name: "Aniqa Tabassum",
      email: "aniqa.tabassum@bracu.ac.bd",
      initial: "AQT",
    },
    {
      department: "CSE",
      id: "fac-cse-aqu",
      name: "Mr. Md. Aquib Azmain",
      email: "aquib.azmain@bracu.ac.bd",
      initial: "AQU",
    },
    {
      department: "CSE",
      id: "fac-cse-ard",
      name: "Mr. Ayman Rasheed",
      email: "ayman.rasheed@bracu.ac.bd",
      initial: "ARD",
    },
    {
      department: "CSE",
      id: "fac-cse-arf",
      name: "Mr. Arif Shakil",
      email: "arif.shakil@bracu.ac.bd",
      initial: "ARF",
    },
    {
      department: "CSE",
      id: "fac-cse-arpd",
      name: "Arpa Roy Dastider",
      email: "arpa.roy@bracu.ac.bd",
      initial: "ARPD",
    },
    {
      department: "CSE",
      id: "fac-cse-art",
      name: "Atanu Roy",
      email: "atanu.roy@bracu.ac.bd",
      initial: "ART",
    },
    {
      department: "CSE",
      id: "fac-cse-asa",
      name: "Dr. Md. Ashraful Alam",
      email: "ashraful.alam@bracu.ac.bd",
      initial: "ASA",
    },
    {
      department: "CSE",
      id: "fac-cse-asak",
      name: "Arnob Saha Ankon",
      email: "arnob.ankon@bracu.ac.bd",
      initial: "ASAK",
    },
    {
      department: "CSE",
      id: "fac-cse-asrf",
      name: "Ashraful Islam Shanto Sikder",
      email: "ashraful.islam@bracu.ac.bd",
      initial: "ASRF",
    },
    {
      department: "CSE",
      id: "fac-cse-aty",
      name: "Ateya Ahmed Subarna",
      email: "ateya.ahmed@bracu.ac.bd",
      initial: "ATY",
    },
    {
      department: "CSE",
      id: "fac-cse-avb",
      name: "Mr. Avinandan Banerjee",
      email: "avinandan@bracu.ac.bd",
      initial: "AVB",
    },
    {
      department: "CSE",
      id: "fac-cse-ayo",
      name: "Ariyan Hossain",
      email: "ariyan.hossain@bracu.ac.bd",
      initial: "AYO",
    },
    {
      department: "CSE",
      id: "fac-cse-bdh",
      name: "Mr. Mohammad Badrul Hossain",
      email: "badrul.hossain@bracu.ac.bd",
      initial: "BDH",
    },
    {
      department: "CSE",
      id: "fac-cse-bijs",
      name: "Bijoy Ahmed Saiem",
      email: "bijoy.saiem@bracu.ac.bd",
      initial: "BIJS",
    },
    {
      department: "CSE",
      id: "fac-cse-cmr",
      name: "Dr. Chowdhury Mofizur Rahman",
      email: "rahman.mofizur@bracu.ac.bd",
      initial: "CMR",
    },
    {
      department: "CSE",
      id: "fac-cse-dfd",
      name: "Mr. Dibyo Fabian Dofadar",
      email: "fabian.dofadar@bracu.ac.bd",
      initial: "DFD",
    },
    {
      department: "CSE",
      id: "fac-cse-ehq",
      name: "Ehtashamul Haque",
      email: "ehtashamul.haque@bracu.ac.bd",
      initial: "EHQ",
    },
    {
      department: "CSE",
      id: "fac-cse-esf",
      name: "Eshat Fareeha",
      email: "ext.eshat.fareeha@bracu.ac.bd",
      initial: "ESF",
    },
    {
      department: "CSE",
      id: "fac-cse-fars",
      name: "Ahmad Farhan Shahriar Chowdhury",
      email: "farhan.shahriar@bracu.ac.bd",
      initial: "FARS",
    },
    {
      department: "CSE",
      id: "fac-cse-fdc",
      name: "Dr. Farida Chowdhury",
      email: "farida.chowdhury@bracu.ac.bd",
      initial: "FDC",
    },
    {
      department: "CSE",
      id: "fac-cse-fdm",
      name: "Md Fardin Rahman Ami",
      email: "ext.fardin.rahman@bracu.ac.bd",
      initial: "FDM",
    },
    {
      department: "CSE",
      id: "fac-cse-fdz",
      name: "Fardin Zaman",
      email: "ext.fardin.zaman@bracu.ac.bd",
      initial: "FDZ",
    },
    {
      department: "CSE",
      id: "fac-cse-fek",
      name: "Farden Ehsan Khan",
      email: "farden.khan@bracu.ac.bd",
      initial: "FEK",
    },
    {
      department: "CSE",
      id: "fac-cse-ffu",
      name: "Farhan Faruk",
      email: "farhan.faruk@bracu.ac.bd",
      initial: "FFU",
    },
    {
      department: "CSE",
      id: "fac-cse-ffr",
      name: "Md. Fatin Ishraq Faruqui",
      email: "md.fatin@bracu.ac.bd",
      initial: "FFR",
    },
    {
      department: "CSE",
      id: "fac-cse-fgz",
      name: "Mr. Md. Fakhruddin Gazzali",
      email: "fakhruddin.gazzali@bracu.ac.bd",
      initial: "FGZ",
    },
    {
      department: "CSE",
      id: "fac-cse-fic",
      name: "Fatiha Ishrar Chowdhury",
      email: "fatiha.ishrar@bracu.ac.bd",
      initial: "FIC",
    },
    {
      department: "CSE",
      id: "fac-cse-fys",
      name: "Dr. Farig Yousuf Sadeque",
      email: "farig.sadeque@bracu.ac.bd",
      initial: "FYS",
    },
    {
      department: "CSE",
      id: "fac-cse-gra",
      name: "Dr. Md. Golam Rabiul Alam",
      email: "rabiul.alam@bracu.ac.bd",
      initial: "GRA",
    },
    {
      department: "CSE",
      id: "fac-cse-hfn",
      name: "Sheikh Araf Noshin",
      email: "araf.noshin@bracu.ac.bd",
      initial: "HFN",
    },
    {
      department: "CSE",
      id: "fac-cse-hmh",
      name: "Mir Hamidul Hussain",
      email: "hamidul.hussain@bracu.ac.bd",
      initial: "HMH",
    },
    {
      department: "CSE",
      id: "fac-cse-iba",
      name: "Mr. Md. Imran Bin Azad",
      email: "imran.azad@bracu.ac.bd",
      initial: "IBA",
    },
    {
      department: "CSE",
      id: "fac-cse-ibu",
      name: "Ms. Ipshita Bonhi Upoma",
      email: "ipshita.upoma@bracu.ac.bd",
      initial: "IBU",
    },
    {
      department: "CSE",
      id: "fac-cse-irza",
      name: "Md. Irtiza Hossain",
      email: "ext.irtiza.hossain@bracu.ac.bd",
      initial: "IRZA",
    },
    {
      department: "CSE",
      id: "fac-cse-khr",
      name: "Dr. Md. Khalilur Rahman",
      email: "khalilur@bracu.ac.bd",
      initial: "KHR",
    },
    {
      department: "CSE",
      id: "fac-cse-kks",
      name: "Md. Khaliduzzaman Khan Samrat",
      email: "md.khaliduzzaman@bracu.ac.bd",
      initial: "KKS",
    },
    {
      department: "CSE",
      id: "fac-cse-kni",
      name: "Ms. Khondoker Nazia Iqbal",
      email: "nazia.iqbal@bracu.ac.bd",
      initial: "KNI",
    },
    {
      department: "CSE",
      id: "fac-cse-kyk",
      name: "Dr. Mohammad Kaykobad",
      email: "kaykobad@bracu.ac.bd",
      initial: "KYK",
    },
    {
      department: "CSE",
      id: "fac-cse-kzmn",
      name: "Kazi Kamruzzaman Rabbi",
      email: "kazi.kamruzzaman@bracu.ac.bd",
      initial: "KZMN",
    },
    {
      department: "CSE",
      id: "fac-cse-lbbh",
      name: "Labib Hasan Khan",
      email: "labib.hasan@bracu.ac.bd",
      initial: "LBBH",
    },
    {
      department: "CSE",
      id: "fac-cse-lmi",
      name: "Lamiah Israt",
      email: "lamiah.israt@bracu.ac.bd",
      initial: "LMI",
    },
    {
      department: "CSE",
      id: "fac-cse-lrk",
      name: "Lara khanom",
      email: "lara.khanom@bracu.ac.bd",
      initial: "LRK",
    },
    {
      department: "CSE",
      id: "fac-cse-maf",
      name: "MD ASIF",
      email: "ext.md.asif@bracu.ac.bd",
      initial: "MAF",
    },
    {
      department: "CSE",
      id: "fac-cse-mafz",
      name: "Mehnaz Ara Fazal",
      email: "ext.mehnaz.fazal@bracu.ac.bd",
      initial: "MAFZ",
    },
    {
      department: "CSE",
      id: "fac-cse-mahr",
      name: "Mahrin Tasfe",
      email: "mahrin.tasfe@bracu.ac.bd",
      initial: "MAHR",
    },
    {
      department: "CSE",
      id: "fac-cse-mahs",
      name: "Md Arif Hasan",
      email: "arif.hasan@bracu.ac.bd",
      initial: "MAHS",
    },
    {
      department: "CSE",
      id: "fac-cse-majij",
      name: "Majisha Jahan Disha",
      email: "majisha.jahan@bracu.ac.bd",
      initial: "MAJIJ",
    },
    {
      department: "CSE",
      id: "fac-cse-mao",
      name: "Mirza Abdullah Al Noman",
      email: "mirza.abdullah@bracu.ac.bd",
      initial: "MAO",
    },
    {
      department: "CSE",
      id: "fac-cse-mazw",
      name: "Mirza Azwad Wakil",
      email: "ext.azwad.wakil@bracu.ac.bd",
      initial: "MAZW",
    },
    {
      department: "CSE",
      id: "fac-cse-mdf",
      name: "Mr. Mohammad Fahim",
      email: "mohammad.fahim@bracu.ac.bd",
      initial: "MDF",
    },
    {
      department: "CSE",
      id: "fac-cse-mhde",
      name: "Mehedi Hasan Emo",
      email: "mehedi.emo@bracu.ac.bd",
      initial: "MHDE",
    },
    {
      department: "CSE",
      id: "fac-cse-mhsk",
      name: "Maharin Mosfakin",
      email: "ext.maharin.mosfakin@bracu.ac.bd",
      initial: "MHSK",
    },
    {
      department: "CSE",
      id: "fac-cse-mhy",
      name: "Abu Musa Al Ashary",
      email: "ext.abu.musa@bracu.ac.bd",
      initial: "MHY",
    },
    {
      department: "CSE",
      id: "fac-cse-mny",
      name: "Dr. Muhammad Nur Yanhaona",
      email: "nur.yanhaona@bracu.ac.bd",
      initial: "MNY",
    },
    {
      department: "CSE",
      id: "fac-cse-mom",
      name: "Md. Moynul Asik Moni",
      email: "moynul.moni@bracu.ac.bd",
      initial: "MOM",
    },
    {
      department: "CSE",
      id: "fac-cse-mria",
      name: "Ummay Maria Muna",
      email: "maria.muna@bracu.ac.bd",
      initial: "MRIA",
    },
    {
      department: "CSE",
      id: "fac-cse-msa",
      name: "Dr. Matin Saad Abdullah",
      email: "mabdullah@bracu.ac.bd",
      initial: "MSA",
    },
    {
      department: "CSE",
      id: "fac-cse-msah",
      name: "Dr. Md. Sakir Hossain",
      email: "sakir.hossain@bracu.ac.bd",
      initial: "MSAH",
    },
    {
      department: "CSE",
      id: "fac-cse-msma",
      name: "Mr. Md. Shamim Mia",
      email: "shamim.mia@bracu.ac.bd",
      initial: "MSMA",
    },
    {
      department: "CSE",
      id: "fac-cse-mtot",
      name: "Md Toky Tazwar",
      email: "ext.toky.tazwar@bracu.ac.bd",
      initial: "MTOT",
    },
    {
      department: "CSE",
      id: "fac-cse-mtsm",
      name: "MD. MUHTASIM MAHMUD",
      email: "muhtasim.mahmud@bracu.ac.bd",
      initial: "MTSM",
    },
    {
      department: "CSE",
      id: "fac-cse-munr",
      name: "A B M Muntasir Rahman",
      email: "abm.muntasir@bracu.ac.bd",
      initial: "MUNR",
    },
    {
      department: "CSE",
      id: "fac-cse-mvh",
      name: "Mohammad Naveed Hossain",
      email: "mohammad.naveed@bracu.ac.bd",
      initial: "MVH",
    },
    {
      department: "CSE",
      id: "fac-cse-mzw",
      name: "Maazin Munawar",
      email: "ext.maazin.munawar@bracu.ac.bd",
      initial: "MZW",
    },
    {
      department: "CSE",
      id: "fac-cse-nafr",
      name: "Md Nafiu Rahman",
      email: "nafiu.rahman@bracu.ac.bd",
      initial: "NAFR",
    },
    {
      department: "CSE",
      id: "fac-cse-nahc",
      name: "Asif Hasan Chowdhury",
      email: "asif.hasan@bracu.ac.bd",
      initial: "NAHC",
    },
    {
      department: "CSE",
      id: "fac-cse-narc",
      name: "Atonu Roy Chowdhury",
      email: "atonuroy.chowdhury@bracu.ac.bd",
      initial: "NARC",
    },
    {
      department: "CSE",
      id: "fac-cse-nast",
      name: "Nazmus Sakib Touhid",
      email: "nazmus.touhid@bracu.ac.bd",
      initial: "NAST",
    },
    {
      department: "CSE",
      id: "fac-cse-nbd",
      name: "Dr. Badhan Das",
      email: "badhan.das@bracu.ac.bd",
      initial: "NBD",
    },
    {
      department: "CSE",
      id: "fac-cse-ndt",
      name: "NIRJHOR DATTA",
      email: "nirjhor.datta@bracu.ac.bd",
      initial: "NDT",
    },
    {
      department: "CSE",
      id: "fac-cse-nff",
      name: "Nafiz Imtiaz Rafin",
      email: "ext.nafiz.rafin@bracu.ac.bd",
      initial: "NFF",
    },
    {
      department: "CSE",
      id: "fac-cse-nfmk",
      name: "Md. Saif Mokarrom",
      email: "saif.mokarrom@bracu.ac.bd",
      initial: "NFMK",
    },
    {
      department: "CSE",
      id: "fac-cse-nfs",
      name: "Nafis Faisal",
      email: "nafis.faisal@bracu.ac.bd",
      initial: "NFS",
    },
    {
      department: "CSE",
      id: "fac-cse-nhbn",
      name: "Hamim Ibne Nasim",
      email: "hamim.nasim@bracu.ac.bd",
      initial: "NHBN",
    },
    {
      department: "CSE",
      id: "fac-cse-nkbs",
      name: "Kefaya Benta Shahnoor",
      email: "kefaya.shahnoor@bracu.ac.bd",
      initial: "NKBS",
    },
    {
      department: "CSE",
      id: "fac-cse-nkma",
      name: "K. M. Azwad Hossain",
      email: "azwad.hossain@bracu.ac.bd",
      initial: "NKMA",
    },
    {
      department: "CSE",
      id: "fac-cse-nlam",
      name: "Namirul Islam",
      email: "namirul.islam@bracu.ac.bd",
      initial: "NLAM",
    },
    {
      department: "CSE",
      id: "fac-cse-nlh",
      name: "Niloy Farhan",
      email: "niloy.farhan@bracu.ac.bd",
      initial: "NLH",
    },
    {
      department: "CSE",
      id: "fac-cse-nmmr",
      name: "MD MIZANUR RAHMAN MUSTAKIM",
      email: "mizanur.mustakim@bracu.ac.bd",
      initial: "NMMR",
    },
    {
      department: "CSE",
      id: "fac-cse-nmp",
      name: "Namira Mustafiz Pranty",
      email: "ext.namira.pranty@bracu.ac.bd",
      initial: "NMP",
    },
    {
      department: "CSE",
      id: "fac-cse-nntn",
      name: "Naima Tahsin Nodi",
      email: "naima.tahsin@bracu.ac.bd",
      initial: "NNTN",
    },
    {
      department: "CSE",
      id: "fac-cse-nqm",
      name: "Md Nafiz Ishtiaque Mahee",
      email: "ext.nafiz.ishtiaque@bracu.ac.bd",
      initial: "NQM",
    },
    {
      department: "CSE",
      id: "fac-cse-nrhb",
      name: "Ruhan Habib",
      email: "ruhan.habib@bracu.ac.bd",
      initial: "NRHB",
    },
    {
      department: "CSE",
      id: "fac-cse-nrt",
      name: "Nusrat Zaman Raya",
      email: "ext.nusrat.raya@bracu.ac.bd",
      initial: "NRT",
    },
    {
      department: "CSE",
      id: "fac-cse-nrzr",
      name: "Riazul Islam Rifat",
      email: "riazul.islam@bracu.ac.bd",
      initial: "NRZR",
    },
    {
      department: "CSE",
      id: "fac-cse-ntr",
      name: "Ms. Narzu Tarannum",
      email: "narzu.tarannum@bracu.ac.bd",
      initial: "NTR",
    },
    {
      department: "CSE",
      id: "fac-cse-nur",
      name: "Nur Mohammad Shaon",
      email: "nur.shaon@bracu.ac.bd",
      initial: "NUR",
    },
    {
      department: "CSE",
      id: "fac-cse-nwt",
      name: "Nowshin Tabassum",
      email: "ext.nowshin.tabassum@bracu.ac.bd",
      initial: "NWT",
    },
    {
      department: "CSE",
      id: "fac-cse-nzrf",
      name: "Niaz Ashraf Khan",
      email: "niaz.ashraf@bracu.ac.bd",
      initial: "NZRF",
    },
    {
      department: "CSE",
      id: "fac-cse-nzu",
      name: "Nazmul Islam",
      email: "nazmul.islam1@bracu.ac.bd",
      initial: "NZU",
    },
    {
      department: "CSE",
      id: "fac-cse-pbk",
      name: "Mr. Partha Bhoumik",
      email: "partha.bhoumik@bracu.ac.bd",
      initial: "PBK",
    },
    {
      department: "CSE",
      id: "fac-cse-pds",
      name: "Mr. Purbayan Das",
      email: "purbayan.das@bracu.ac.bd",
      initial: "PDS",
    },
    {
      department: "CSE",
      id: "fac-cse-pln",
      name: "Pollock Nag",
      email: "pollock.nag@bracu.ac.bd",
      initial: "PLN",
    },
    {
      department: "CSE",
      id: "fac-cse-prc",
      name: "Pratick Roy Chowdhuruy",
      email: "ext.pratick.roy@bracu.ac.bd",
      initial: "PRC",
    },
    {
      department: "CSE",
      id: "fac-cse-quza",
      name: "Quazi Ashikur Rahman",
      email: "quazi.ashikur@bracu.ac.bd",
      initial: "QUZA",
    },
    {
      department: "CSE",
      id: "fac-cse-raha",
      name: "Farzana Reefat Raha",
      email: "reefat.raha@bracu.ac.bd",
      initial: "RAHA",
    },
    {
      department: "CSE",
      id: "fac-cse-rak",
      name: "Mr. Rubayat Ahmed Khan",
      email: "rubayat.ahmed@bracu.ac.bd",
      initial: "RAK",
    },
    {
      department: "CSE",
      id: "fac-cse-rao",
      name: "Mohammed Radoan",
      email: "ext.mohammed.radoan@bracu.ac.bd",
      initial: "RAO",
    },
    {
      department: "CSE",
      id: "fac-cse-rbr",
      name: "Mr. Rakin Bin Rabbani",
      email: "rakin.rabbani@bracu.ac.bd",
      initial: "RBR",
    },
    {
      department: "CSE",
      id: "fac-cse-rds",
      name: "Rantu Das",
      email: "ext.rantu.das@bracu.ac.bd",
      initial: "RDS",
    },
    {
      department: "CSE",
      id: "fac-cse-rdw",
      name: "Redowanul Akbar",
      email: "redowanul.akbar@bracu.ac.bd",
      initial: "RDW",
    },
    {
      department: "CSE",
      id: "fac-cse-rff",
      name: "Rafid Ahnaf",
      email: "rafid.ahnaf@bracu.ac.bd",
      initial: "RFF",
    },
    {
      department: "CSE",
      id: "fac-cse-rfr",
      name: "Md. Rifat Rahman",
      email: "rifat.rahman@bracu.ac.bd",
      initial: "RFR",
    },
    {
      department: "CSE",
      id: "fac-cse-rfts",
      name: "Rifa Tasfiya",
      email: "rifa.tasfiya@bracu.ac.bd",
      initial: "RFTS",
    },
    {
      department: "CSE",
      id: "fac-cse-rkbm",
      name: "Mohammad Rakibul Hasan Mahin",
      email: "mohammad.rakibul@bracu.ac.bd",
      initial: "RKBM",
    },
    {
      department: "CSE",
      id: "fac-cse-rkbr",
      name: "Rakib Kibria",
      email: "rakib.kibria@bracu.ac.bd",
      initial: "RKBR",
    },
    {
      department: "CSE",
      id: "fac-cse-rkn",
      name: "Raisul Kabir News",
      email: "raisul.kabir@bracu.ac.bd",
      initial: "RKN",
    },
    {
      department: "CSE",
      id: "fac-cse-rrh",
      name: "Mr. Rafeed Rahman",
      email: "rahman.rafeed@bracu.ac.bd",
      initial: "RRH",
    },
    {
      department: "CSE",
      id: "fac-cse-rss",
      name: "Rafiad Sadat Shahir",
      email: "rafiad.shahir@bracu.ac.bd",
      initial: "RSS",
    },
    {
      department: "CSE",
      id: "fac-cse-sada",
      name: "Sadif Ahmed",
      email: "sadif.ahmed@bracu.ac.bd",
      initial: "SADA",
    },
    {
      department: "CSE",
      id: "fac-cse-sadf",
      name: "Saadat Rafid Ahmed",
      email: "saadat.ahmed@bracu.ac.bd",
      initial: "SADF",
    },
    {
      department: "CSE",
      id: "fac-cse-sas",
      name: "Dr. Md. Shafiul Alam Shuvo",
      email: "ext.shafiul.shuvo@bracu.ac.bd",
      initial: "SAS",
    },
    {
      department: "CSE",
      id: "fac-cse-sbb",
      name: "Md. Sabbir Ahmed",
      email: "sabbir.ahmed@bracu.ac.bd",
      initial: "SBB",
    },
    {
      department: "CSE",
      id: "fac-cse-sbhn",
      name: "Mr. Md Sabbir Hossain",
      email: "sabbir.hossain@bracu.ac.bd",
      initial: "SBHN",
    },
    {
      department: "CSE",
      id: "fac-cse-sdas",
      name: "Sowmitra Das",
      email: "sowmitra.das@bracu.ac.bd",
      initial: "SDAS",
    },
    {
      department: "CSE",
      id: "fac-cse-sdf",
      name: "Dr. Md Sadek Ferdous",
      email: "sadek.ferdous@bracu.ac.bd",
      initial: "SDF",
    },
    {
      department: "CSE",
      id: "fac-cse-sdl",
      name: "Shadmin Sultana",
      email: "shadmin.sultana@bracu.ac.bd",
      initial: "SDL",
    },
    {
      department: "CSE",
      id: "fac-cse-sdq",
      name: "Mr. Md. Saiful Bari Siddiqui",
      email: "saiful.bari@bracu.ac.bd",
      initial: "SDQ",
    },
    {
      department: "CSE",
      id: "fac-cse-sds",
      name: "Mr. Shadman Shahriar",
      email: "shadman.shahriar@bracu.ac.bd",
      initial: "SDS",
    },
    {
      department: "CSE",
      id: "fac-cse-sef",
      name: "Sheikh Iftekhar Ahmed",
      email: "ext.sheikh.ahmed@bracu.ac.bd",
      initial: "SEF",
    },
    {
      department: "CSE",
      id: "fac-cse-shbk",
      name: "Sahib Kowsar",
      email: "sahib.kowsar@bracu.ac.bd",
      initial: "SHBK",
    },
    {
      department: "CSE",
      id: "fac-cse-shbz",
      name: "Dr. Md Shamsuzzoha Bayzid",
      email: "ext.shams.bayzid@bracu.ac.bd",
      initial: "SHBZ",
    },
    {
      department: "CSE",
      id: "fac-cse-sjm",
      name: "Sajid Imam Mahir",
      email: "ext.sajid.mahir@bracu.ac.bd",
      initial: "SJM",
    },
    {
      department: "CSE",
      id: "fac-cse-skib",
      name: "Nazmus Sakib Ahmed",
      email: "nazmus.sakib@bracu.ac.bd",
      initial: "SKIB",
    },
    {
      department: "CSE",
      id: "fac-cse-skz",
      name: "Dr. Sadia Hamid Kazi",
      email: "skazi@bracu.ac.bd",
      initial: "SKZ",
    },
    {
      department: "CSE",
      id: "fac-cse-smds",
      name: "Soumitra Das",
      email: "ext.soumitra.das@bracu.ac.bd",
      initial: "SMDS",
    },
    {
      department: "CSE",
      id: "fac-cse-smur",
      name: "Samiur Rahman",
      email: "rahman.samiur@bracu.ac.bd",
      initial: "SMUR",
    },
    {
      department: "CSE",
      id: "fac-cse-smya",
      name: "Sumaiya",
      email: "sumaiya@bracu.ac.bd",
      initial: "SMYA",
    },
    {
      department: "CSE",
      id: "fac-cse-sosb",
      name: "Soumya Swagata Biswas",
      email: "soumya.swagata@bracu.ac.bd",
      initial: "SOSB",
    },
    {
      department: "CSE",
      id: "fac-cse-srj",
      name: "Ms. Mehnaz Seraj",
      email: "seraj.mehnaz@bracu.ac.bd",
      initial: "SRJ",
    },
    {
      department: "CSE",
      id: "fac-cse-sru",
      name: "Mr. Shakir Rouf",
      email: "shakir.rouf@bracu.ac.bd",
      initial: "SRU",
    },
    {
      department: "CSE",
      id: "fac-cse-sskd",
      name: "Sheikh Samiul Kadir",
      email: "ext.samiul.kadir@bracu.ac.bd",
      initial: "SSKD",
    },
    {
      department: "CSE",
      id: "fac-cse-stnm",
      name: "Sanjida Tasnim",
      email: "sanjida.tasnim@bracu.ac.bd",
      initial: "STNM",
    },
    {
      department: "CSE",
      id: "fac-cse-sue",
      name: "Sukarna Sarker",
      email: "sukarna.sarkar@bracu.ac.bd",
      initial: "SUE",
    },
    {
      department: "CSE",
      id: "fac-cse-swg",
      name: "Mr. Swattic Ghose",
      email: "swattic.ghose@bracu.ac.bd",
      initial: "SWG",
    },
    {
      department: "CSE",
      id: "fac-cse-swk",
      name: "Dr. Swakkhar Shatabda",
      email: "swakkhar.shatabda@bracu.ac.bd",
      initial: "SWK",
    },
    {
      department: "CSE",
      id: "fac-cse-szd",
      name: "Md. Shazid Bin Mahbub",
      email: "shazid.mahbub@bracu.ac.bd",
      initial: "SZD",
    },
    {
      department: "CSE",
      id: "fac-cse-szz",
      name: "Sazzadul Islam",
      email: "sazzadul.islam@bracu.ac.bd",
      initial: "SZZ",
    },
    {
      department: "CSE",
      id: "fac-cse-tap",
      name: "Ms. Tasnim Ahsan Prome",
      email: "tasnim.ahsan@bracu.ac.bd",
      initial: "TAP",
    },
    {
      department: "CSE",
      id: "fac-cse-tav",
      name: "Tarvir Anjum Aditto",
      email: "tarvir.anjum@bracu.ac.bd",
      initial: "TAV",
    },
    {
      department: "CSE",
      id: "fac-cse-taw",
      name: "Mr. Md. Tawhid Anwar",
      email: "tawhid.anwar@bracu.ac.bd",
      initial: "TAW",
    },
    {
      department: "CSE",
      id: "fac-cse-thr",
      name: "Tahsin Tanim Ramisha",
      email: "ext.tahsin.ramisha@bracu.ac.bd",
      initial: "THR",
    },
    {
      department: "CSE",
      id: "fac-cse-tlq",
      name: "Dr. Taiabul Haque",
      email: "taiabul.haque@bracu.ac.bd",
      initial: "TLQ",
    },
    {
      department: "CSE",
      id: "fac-cse-tmd",
      name: "Mr. Tamkin Mahmud Tan",
      email: "tamkin.mahmud@bracu.ac.bd",
      initial: "TMD",
    },
    {
      department: "CSE",
      id: "fac-cse-tnf",
      name: "Tanhiat Fatema Afnan",
      email: "tanhiat.fatema@bracu.ac.bd",
      initial: "TNF",
    },
    {
      department: "CSE",
      id: "fac-cse-tnmf",
      name: "Ms. Tasnim Ferdous",
      email: "tasnim.ferdous@bracu.ac.bd",
      initial: "TNMF",
    },
    {
      department: "CSE",
      id: "fac-cse-trz",
      name: "Mr. Md. Tanzim Reza",
      email: "tanzim.reza@bracu.ac.bd",
      initial: "TRZ",
    },
    {
      department: "CSE",
      id: "fac-cse-tse",
      name: "Tasneem Mazhar",
      email: "tasneem.mazhar@bracu.ac.bd",
      initial: "TSE",
    },
    {
      department: "CSE",
      id: "fac-cse-tsm",
      name: "Mr. Mirza Md. Tanjim Shorif Mugdho",
      email: "mirza.mugdho@bracu.ac.bd",
      initial: "TSM",
    },
    {
      department: "CSE",
      id: "fac-cse-tvrr",
      name: "Tanveer Rahman",
      email: "tanveer.rahman@bracu.ac.bd",
      initial: "TVRR",
    },
    {
      department: "CSE",
      id: "fac-cse-twk",
      name: "Towshik Anam Taj",
      email: "towshik.taj@bracu.ac.bd",
      initial: "TWK",
    },
    {
      department: "CSE",
      id: "fac-cse-ujt",
      name: "Umme Jannat Taposhi",
      email: "jannat.taposhi@bracu.ac.bd",
      initial: "UJT",
    },
    {
      department: "CSE",
      id: "fac-cse-utkr",
      name: "Utsha Kumar Roy",
      email: "utsha.roy@bracu.ac.bd",
      initial: "UTKR",
    },
    {
      department: "CSE",
      id: "fac-cse-wbh",
      name: "Waleed Bin Habib Khan",
      email: "ext.waleed.bin@bracu.ac.bd",
      initial: "WBH",
    },
    {
      department: "CSE",
      id: "fac-cse-whmj",
      name: "Wahida Mahjabin",
      email: "wahida.mahjabin@bracu.ac.bd",
      initial: "WHMJ",
    },
    {
      department: "CSE",
      id: "fac-cse-wlv",
      name: "Md.Waseq Alauddin Alvi",
      email: "ext.waseq.alvi@bracu.ac.bd",
      initial: "WLV",
    },
    {
      department: "CSE",
      id: "fac-cse-ynd",
      name: "Yasmin Nadia",
      email: "yasmin.nadia@bracu.ac.bd",
      initial: "YND",
    },
    {
      department: "CSE",
      id: "fac-cse-zaz",
      name: "Ihzaz Abrar Sadik",
      email: "ihzaz.sadik@bracu.ac.bd",
      initial: "ZAZ",
    },
    {
      department: "CSE",
      id: "fac-cse-zbh",
      name: "Md Zayed Bin Zahir Arju",
      email: "zayed.zahir@bracu.ac.bd",
      initial: "ZBH",
    },
    {
      department: "CSE",
      id: "fac-cse-zbyr",
      name: "Zobayer Hasan",
      email: "ext.zobayer.hasan@bracu.ac.bd",
      initial: "ZBYR",
    },
    {
      department: "CSE",
      id: "fac-cse-zhs",
      name: "Mr. Syed Zamil Hasan Shoumo",
      email: "shoumo.hasan@bracu.ac.bd",
      initial: "ZHS",
    },
    {
      department: "CSE",
      id: "fac-cse-zlnm",
      name: "Md. Zulkar Naim",
      email: "zulkar.naim@bracu.ac.bd",
      initial: "ZLNM",
    },
    {
      department: "CSE",
      id: "fac-cse-zmd",
      name: "Mr. Zaber Mohammad",
      email: "zaber.mohammad@bracu.ac.bd",
      initial: "ZMD",
    },
    {
      department: "CSE",
      id: "fac-cse-zyh",
      name: "Zayed Humayun",
      email: "zayed.humayun@bracu.ac.bd",
      initial: "ZYH",
    },
  ],
  defaultProfile: {
    name: "SK Reyad Ali",
    studentId: "24210009",
    email: "sk.reyad.ali@g.bracu.ac.bd",
    program: "BSc in Computer Science",
    university: "BRAC University",
    batch: "",
    startingSemester: "Fall 2024",
    profilePhoto: "",
  },
  defaultSemesters: [
    {
      id: "sem-1781436868699-4f7fb111a8abd",
      number: 1,
      name: "Fall 2024",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437018675-0fe809760a188",
          code: "MAT110",
          status: "completed",
          grade: "A",
          gradePoint: 4,
          facultyId: "fac-1781436937825-8bbac00d50f25",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:36:58.675Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437206372-1d469a44fab4b",
          code: "ENG091",
          status: "completed",
          grade: "P",
          gradePoint: null,
          facultyId: "fac-1781437189834-f0539fecfed908",
          creditsOverride: 0,
          createdAt: "2026-06-14T11:40:06.372Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437283293-c8f99a3357398",
          code: "PHY111",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1781437261874-346c0f72503f5",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:41:23.293Z",
        },
      ],
    },
    {
      id: "sem-1781437466439-4b6742f0fe34e8",
      number: 2,
      name: "Spring 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437513933-abcecc1a4f17d",
          code: "CSE110",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1781436964511-a4e5c8ec351578",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:45:13.933Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437587085-1d4ac4a5594f5",
          code: "CSE230",
          status: "completed",
          grade: "B-",
          gradePoint: 2.7,
          facultyId: "fac-1781437570512-e64737646179f",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:46:27.085Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1781437652989-f964691e032c7",
          code: "ENG101",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1781437644904-c75b0063affff8",
          creditsOverride: 3,
          createdAt: "2026-06-14T11:47:32.989Z",
        },
      ],
    },
    {
      id: "sem-1783432111862-4741c1f477c9f",
      number: 3,
      name: "Summer 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432144263-5ff1ee67c4619",
          code: "CSE111",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1781436964511-a4e5c8ec351578",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:49:04.263Z",
        },
        {
          repeatType: "RP",
          countsInCGPA: true,
          id: "attempt-1783432217927-8733dc36e3fff8",
          code: "CSE230",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432205256-e1f6702fc65f",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:50:17.927Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432352261-20aba5e06d204",
          code: "STA201",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432339836-bbcfd92172be8",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:52:32.261Z",
        },
      ],
    },
    {
      id: "sem-1783432409611-d4050ac43f4b8",
      number: 4,
      name: "Fall 2025",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432503134-33cba58df6084",
          code: "BNG103",
          status: "completed",
          grade: "A",
          gradePoint: 4,
          facultyId: "fac-1783432481590-a1a71cfbecaac",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:55:03.134Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432721683-69d89d03ba943",
          code: "EMB101",
          status: "completed",
          grade: "A+",
          gradePoint: 4,
          facultyId: "fac-1783432546878-11dd065e7ed6b8",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:58:41.683Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432738133-beed8bf2d762f",
          code: "ENG102",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432703649-d66da0546e5b48",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:58:58.133Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432751451-d79691b9b5ff18",
          code: "HUM103",
          status: "completed",
          grade: "A-",
          gradePoint: 3.7,
          facultyId: "fac-1783432675055-15eaa50eab3a68",
          creditsOverride: 3,
          createdAt: "2026-07-07T13:59:11.451Z",
        },
      ],
    },
    {
      id: "sem-1783432764662-8010ec1295f3d8",
      number: 5,
      name: "Spring 2026",
      courses: [
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783432993538-8c990b15c21a78",
          code: "CSE260",
          status: "completed",
          grade: "B-",
          gradePoint: 2.7,
          facultyId: "fac-1783432813473-cf6406aea417f8",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:13.538Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783433007013-8ad82ae9d0f4f",
          code: "MAT120",
          status: "completed",
          grade: "B+",
          gradePoint: 3.3,
          facultyId: "fac-1783432901276-29aa69f2fe53a",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:27.013Z",
        },
        {
          repeatType: "",
          countsInCGPA: true,
          id: "attempt-1783433016884-8b0b40dd687888",
          code: "PHY112",
          status: "completed",
          grade: "D+",
          gradePoint: 1.3,
          facultyId: "fac-1783432976002-b18d405ef4f708",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:03:36.884Z",
        },
      ],
    },
    {
      id: "sem-1783433071283-772cfc3eadfb18",
      number: 6,
      name: "Summer 2026",
      courses: [
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433361358-da7041b513eb9",
          code: "CSE220",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433107824-7a32be6683d608",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:21.358Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433388194-7fd4faa8798358",
          code: "CSE320",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433205156-e1a1c4255634d8",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:48.194Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433399692-c9aa5bfac80e38",
          code: "MAT216",
          status: "current",
          grade: "",
          gradePoint: null,
          facultyId: "fac-1783433337163-9b0bda7bc8156",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:09:59.692Z",
        },
      ],
    },
    {
      id: "sem-1783433539523-13b6d50a9c0e6",
      number: 7,
      name: "Fall 2026",
      courses: [
        {
          repeatType: "RP",
          countsInCGPA: false,
          id: "attempt-1783433553594-464dc84d91a9f",
          code: "CSE260",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:33.594Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433561259-af37fb6c004c3",
          code: "CSE221",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:41.259Z",
        },
        {
          repeatType: "",
          countsInCGPA: false,
          id: "attempt-1783433571034-03a9bab0eb853",
          code: "MAT215",
          status: "planned",
          grade: "",
          gradePoint: null,
          facultyId: "",
          creditsOverride: 3,
          createdAt: "2026-07-07T14:12:51.034Z",
        },
      ],
    },
  ],
};

function resolveReportWebsiteUrl(configuredUrl, currentHref) {
  const configured = String(configuredUrl || "").trim();
  if (configured) return configured;

  try {
    const current = new URL(String(currentHref || ""));
    if (current.protocol === "http:" || current.protocol === "https:") {
      return `${current.origin}${current.pathname}`;
    }
  } catch {}

  return "this website";
}

if (typeof globalThis !== "undefined") {
  globalThis.DEFAULT_DATA = DEFAULT_DATA;
  globalThis.resolveReportWebsiteUrl = resolveReportWebsiteUrl;
}

if (typeof module === "object" && module.exports) {
  module.exports = { DEFAULT_DATA, resolveReportWebsiteUrl };
}
