begin;

-- Seed the existing application defaults into the shared catalog. Existing
-- administrator-created rows win because every insert uses DO NOTHING.
-- Roadmap-only ELECTIVE/COD slots are curriculum placeholders, not courses.

-- catalog-seed:departments:start
insert into public.catalog_departments (id, name, color)
values
  ('CSE', 'Computer Science and Engineering', 'blue'),
  ('MNS', 'Mathematics and Natural Sciences', 'teal'),
  ('BIL', 'BRAC Institute of Languages', 'amber'),
  ('BBS', 'BRAC Business School', 'purple'),
  ('GED', 'General Education', 'slate'),
  ('OTH', 'Other / Custom', 'gray')
on conflict (id) do nothing;
-- catalog-seed:departments:end

-- catalog-seed:courses:start
insert into public.catalog_courses (
  code, title, credits, department, category, roadmap_level, roadmap_order,
  hard_prerequisites, soft_prerequisites, source_note, is_roadmap_slot
)
values
  ('CSE110', 'Programming Language I', 3, 'CSE', 'program-core', 1, 1, '{}'::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('MAT110', 'MATH I: Differential Calculus and Co-ordinate Geometry', 3, 'MNS', 'gened', 1, 2, '{}'::text[], '{}'::text[], 'Degree Plan GenEd Math', false),
  ('ENG101', 'English Fundamentals', 3, 'BIL', 'gened', 1, 3, '{}'::text[], '{}'::text[], 'Degree Plan GenEd English', false),
  ('PHY111', 'Principles of Physics I', 3, 'MNS', 'gened', 1, 4, '{}'::text[], '{}'::text[], 'Degree Plan GenEd Life & Physical Sciences', false),
  ('CSE111', 'Programming Language II', 3, 'CSE', 'program-core', 2, 1, array['CSE110']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE230', 'Discrete Mathematics', 3, 'CSE', 'program-core', 2, 2, '{}'::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('STA201', 'Elements of Statistics and Probability', 3, 'MNS', 'gened', 2, 3, '{}'::text[], array['MAT110']::text[], 'Degree Plan GenEd Life & Physical Sciences', false),
  ('PHY112', 'Principles of Physics II', 3, 'MNS', 'school-core', 2, 4, array['PHY111']::text[], '{}'::text[], 'Updated degree plan School Core', false),
  ('BNG103', 'Bangla Language and Literature', 3, 'BIL', 'gened', 3, 1, '{}'::text[], '{}'::text[], 'Updated degree plan Stream 3', false),
  ('EMB101', 'Emergence of Bangladesh', 3, 'GED', 'gened', 3, 2, '{}'::text[], '{}'::text[], 'Updated degree plan Social Sciences option', false),
  ('ENG102', 'English Composition I', 3, 'BIL', 'gened', 3, 3, array['ENG101']::text[], '{}'::text[], 'Degree Plan GenEd English', false),
  ('HUM103', 'Ethics and Culture', 3, 'GED', 'gened', 3, 4, '{}'::text[], '{}'::text[], 'Degree Plan Global Thinking / Humanities', false),
  ('CSE220', 'Data Structures', 3, 'CSE', 'program-core', 4, 1, array['CSE111']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('MAT120', 'MATH II: Integral Calculus and Differential Equations', 3, 'MNS', 'school-core', 4, 2, array['MAT110']::text[], '{}'::text[], 'Updated degree plan School Core', false),
  ('CSE221', 'Algorithms', 3, 'CSE', 'program-core', 5, 1, array['CSE220']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('MAT216', 'MATH IV: Linear Algebra and Fourier Analysis', 3, 'MNS', 'school-core', 5, 2, '{}'::text[], '{}'::text[], 'Updated degree plan School Core', false),
  ('CSE321', 'Operating Systems', 3, 'CSE', 'program-core', 6, 1, array['CSE221']::text[], array['CSE340']::text[], 'Official CS program core / Degree Plan', false),
  ('CSE330', 'Numerical Methods', 3, 'CSE', 'program-core', 6, 2, array['MAT216']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE260', 'Digital Logic Design', 3, 'CSE', 'program-core', 6, 3, '{}'::text[], '{}'::text[], 'Official CS core; prerequisite editable by user', false),
  ('CSE370', 'Database Systems', 3, 'CSE', 'program-core', 7, 1, array['CSE221']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('MAT215', 'MATH III: Complex Variables and Laplace Transformations', 3, 'MNS', 'school-core', 7, 2, '{}'::text[], '{}'::text[], 'Updated degree plan School Core', false),
  ('CSE340', 'Computer Architecture', 3, 'CSE', 'program-core', 7, 3, array['CSE260']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE422', 'Artificial Intelligence', 3, 'CSE', 'program-core', 8, 1, array['CSE221']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE331', 'Automata and Computability', 3, 'CSE', 'program-core', 9, 1, array['CSE221']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE420', 'Compiler Design', 3, 'CSE', 'program-core', 10, 1, array['CSE321', 'CSE331', 'CSE340']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE421', 'Computer Networks', 3, 'CSE', 'program-core', 10, 2, '{}'::text[], array['CSE320']::text[], 'Official CS program core / Degree Plan', false),
  ('CSE423', 'Computer Graphics', 3, 'CSE', 'program-core', 10, 3, array['MAT216']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE470', 'Software Engineering', 3, 'CSE', 'program-core', 11, 1, array['CSE370']::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('CSE400', 'Final-Year Project / Internship / Thesis', 4, 'CSE', 'thesis-project', 11, 2, '{}'::text[], '{}'::text[], 'Official CS program core / Degree Plan', false),
  ('BIO101', 'Biology', 3, 'MNS', 'gened', null, null, '{}'::text[], '{}'::text[], 'GenEd optional Life & Physical Sciences', false),
  ('CHE101', 'Chemistry', 3, 'MNS', 'gened', null, null, '{}'::text[], '{}'::text[], 'GenEd optional Life & Physical Sciences', false),
  ('CSE250', 'Circuits and Electronics', 3, 'CSE', 'program-elective', null, null, '{}'::text[], array['PHY112']::text[], 'Official CS program elective', false),
  ('CSE251', 'Electronic Devices and Circuits', 3, 'CSE', 'program-elective', null, null, array['CSE250']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE310', 'Object Oriented Programming', 3, 'CSE', 'program-elective', null, null, array['CSE111']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE320', 'Data Communication', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE341', 'Microprocessor', 3, 'CSE', 'program-elective', null, null, '{}'::text[], array['CSE340']::text[], 'Official CS program elective', false),
  ('CSE342', 'Computer Systems Engineering', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE350', 'Digital Electronics and Pulse Techniques', 3, 'CSE', 'program-elective', null, null, array['CSE251']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE360', 'Computer Interface', 3, 'CSE', 'program-elective', null, null, array['CSE341']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE390', 'Technical Communication', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE391', 'Programming for the Internet', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE392', 'Signals and Systems', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE410', 'Advanced Programming in UNIX', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE419', 'Programming Languages', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE424', 'Pattern Recognition', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE425', 'Neural Networks', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE426', 'Basic Graph Theory', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE427', 'Machine Learning', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE428', 'Image Processing', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE429', 'Basic Multimedia Theory', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE430', 'Digital Signal Processing', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE431', 'Natural Language Processing', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE432', 'Speech Recognition and Synthesis', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE460', 'VLSI Design', 3, 'CSE', 'program-elective', null, null, array['CSE260']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE461', 'Digital System Design', 3, 'CSE', 'program-elective', null, null, array['CSE260', 'CSE341', 'CSE360']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE462', 'Fault Tolerant Systems', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE471', 'System Analysis and Design', 3, 'CSE', 'program-elective', null, null, array['CSE370']::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE472', 'Human Computer Interface', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE473', 'Decision Support System', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE474', 'Simulation and Modeling', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE490', 'Special Topics / WAN Routing and Technologies', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('CSE491', 'Independent Study', 3, 'CSE', 'program-elective', null, null, '{}'::text[], '{}'::text[], 'Official CS program elective', false),
  ('DEV101', 'Bangladesh Studies / Development Studies', 3, 'GED', 'gened', null, null, '{}'::text[], '{}'::text[], 'GenEd option; not placed on roadmap by default', false),
  ('ENG091', 'Foundation Course in English', 0, 'BIL', 'non-credit', null, null, '{}'::text[], '{}'::text[], 'Updated degree plan / user backup', false),
  ('ENG103', 'Advanced Writing Skills and Presentation', 3, 'BIL', 'gened', null, null, array['ENG102']::text[], '{}'::text[], 'Updated degree plan optional for ENG102 freshers', false),
  ('ENV103', 'Introduction to Environmental Science', 3, 'MNS', 'gened', null, null, '{}'::text[], '{}'::text[], 'GenEd optional Life & Physical Sciences', false)
on conflict (code) do nothing;
-- catalog-seed:courses:end

-- catalog-seed:faculties:start
insert into public.catalog_faculties (initial, name, email, department)
values
  ('SAN', 'Sanjeeda Nazneen', 'sanjeeda@bracu.ac.bd', 'MNS'),
  ('ADU', 'Ahmed Mahir Ruhan', 'ahmed.ruhan@bracu.ac.bd', 'CSE'),
  ('TAO', 'Tanjeela Osmani', 'tanjeela.osmani@bracu.ac.bd', 'BIL'),
  ('TNVR', 'Tanveer Islam', 'ext.priyanka.chak@bracu.ac.bd', 'MNS'),
  ('PSMD', 'Prothito Shovon Majumder', 'prothito.shovon@bracu.ac.bd', 'CSE'),
  ('JUL', 'Md. Julhas Uddin', 'julhas@bracu.ac.bd', 'BIL'),
  ('SLAR', 'Sadiul Arefin Rafi', 'ext.sadiul.rafi@bracu.ac.bd', 'CSE'),
  ('FZZ', 'Farzana Zaman', 'farzana25zaman@gmail.com', 'MNS'),
  ('MCC', 'Chaitee Chakraborty', 'chaitee.chakraborty@bracu.ac.bd', 'GED'),
  ('SWBN', 'Sawban Ibn Farid', 'sawban.farid@bracu.ac.bd', 'GED'),
  ('PRCK', 'Priyanka Chak', null, 'GED'),
  ('JNF', 'Jannatul Ferdous', 'jannatul.ferdous@bracu.ac.bd', 'BIL'),
  ('DZK', 'Dewan Ziaul Karim', 'ziaul.karim@bracu.ac.bd', 'CSE'),
  ('RHR', 'Rifat Hasan Rubel', 'ext.rifat.hasan@bracu.ac.bd', 'MNS'),
  ('TJB', 'Dr. Md Tanjib Atique Khan', 'ext.tanjib.atique@bracu.ac.bd', 'MNS'),
  ('TRZA', 'Tanjim Reza', 'ext.tanjim.reza@bracu.ac.bd', 'CSE'),
  ('SHAH', 'Asif Shahriar', 'asif.shahriar@bracu.ac.bd', 'CSE'),
  ('DLI', 'Dulali Iqbal', 'ext.dulali.iqbal@bracu.ac.bd', 'MNS'),
  ('AAR', 'Mr. Annajiat Alim Rasel', 'annajiat@bracu.ac.bd', 'CSE'),
  ('ACH', 'Dr. Amitabha Chakrabarty', 'amitabha@bracu.ac.bd', 'CSE'),
  ('AFQ', 'Mohammed Ashfaqul Haque', 'ashfaqul.haque@bracu.ac.bd', 'CSE'),
  ('AIB', 'Mr. Md. Abu Ibrahim', 'abu.ibrahim@bracu.ac.bd', 'CSE'),
  ('AJA', 'Mr. Abid Jahan Apon', 'abid.jahan@bracu.ac.bd', 'CSE'),
  ('AKJ', 'Akib Anjum', 'anjum.akib@bracu.ac.bd', 'CSE'),
  ('AKTD', 'Md. Akhtaruzaman Adnan', 'akhtaruzzaman.adnan@bracu.ac.bd', 'CSE'),
  ('ALB', 'Anindita Labonno', 'anindita.labonno@bracu.ac.bd', 'CSE'),
  ('AMK', 'Dr. Abu Mohammad Khan', 'abu.khan@bracu.ac.bd', 'CSE'),
  ('ANKH', 'Anika Ahmed', 'anika.ahmed@bracu.ac.bd', 'CSE'),
  ('ANWE', 'Abdullah Nayem Wasi Emran', 'abdullah.nayem@bracu.ac.bd', 'CSE'),
  ('AQT', 'Aniqa Tabassum', 'aniqa.tabassum@bracu.ac.bd', 'CSE'),
  ('AQU', 'Mr. Md. Aquib Azmain', 'aquib.azmain@bracu.ac.bd', 'CSE'),
  ('ARD', 'Mr. Ayman Rasheed', 'ayman.rasheed@bracu.ac.bd', 'CSE'),
  ('ARF', 'Mr. Arif Shakil', 'arif.shakil@bracu.ac.bd', 'CSE'),
  ('ARPD', 'Arpa Roy Dastider', 'arpa.roy@bracu.ac.bd', 'CSE'),
  ('ART', 'Atanu Roy', 'atanu.roy@bracu.ac.bd', 'CSE'),
  ('ASA', 'Dr. Md. Ashraful Alam', 'ashraful.alam@bracu.ac.bd', 'CSE'),
  ('ASAK', 'Arnob Saha Ankon', 'arnob.ankon@bracu.ac.bd', 'CSE'),
  ('ASRF', 'Ashraful Islam Shanto Sikder', 'ashraful.islam@bracu.ac.bd', 'CSE'),
  ('ATY', 'Ateya Ahmed Subarna', 'ateya.ahmed@bracu.ac.bd', 'CSE'),
  ('AVB', 'Mr. Avinandan Banerjee', 'avinandan@bracu.ac.bd', 'CSE'),
  ('AYO', 'Ariyan Hossain', 'ariyan.hossain@bracu.ac.bd', 'CSE'),
  ('BDH', 'Mr. Mohammad Badrul Hossain', 'badrul.hossain@bracu.ac.bd', 'CSE'),
  ('BIJS', 'Bijoy Ahmed Saiem', 'bijoy.saiem@bracu.ac.bd', 'CSE'),
  ('CMR', 'Dr. Chowdhury Mofizur Rahman', 'rahman.mofizur@bracu.ac.bd', 'CSE'),
  ('DFD', 'Mr. Dibyo Fabian Dofadar', 'fabian.dofadar@bracu.ac.bd', 'CSE'),
  ('EHQ', 'Ehtashamul Haque', 'ehtashamul.haque@bracu.ac.bd', 'CSE'),
  ('ESF', 'Eshat Fareeha', 'ext.eshat.fareeha@bracu.ac.bd', 'CSE'),
  ('FARS', 'Ahmad Farhan Shahriar Chowdhury', 'farhan.shahriar@bracu.ac.bd', 'CSE'),
  ('FDC', 'Dr. Farida Chowdhury', 'farida.chowdhury@bracu.ac.bd', 'CSE'),
  ('FDM', 'Md Fardin Rahman Ami', 'ext.fardin.rahman@bracu.ac.bd', 'CSE'),
  ('FDZ', 'Fardin Zaman', 'ext.fardin.zaman@bracu.ac.bd', 'CSE'),
  ('FEK', 'Farden Ehsan Khan', 'farden.khan@bracu.ac.bd', 'CSE'),
  ('FFU', 'Farhan Faruk', 'farhan.faruk@bracu.ac.bd', 'CSE'),
  ('FFR', 'Md. Fatin Ishraq Faruqui', 'md.fatin@bracu.ac.bd', 'CSE'),
  ('FGZ', 'Mr. Md. Fakhruddin Gazzali', 'fakhruddin.gazzali@bracu.ac.bd', 'CSE'),
  ('FIC', 'Fatiha Ishrar Chowdhury', 'fatiha.ishrar@bracu.ac.bd', 'CSE'),
  ('FYS', 'Dr. Farig Yousuf Sadeque', 'farig.sadeque@bracu.ac.bd', 'CSE'),
  ('GRA', 'Dr. Md. Golam Rabiul Alam', 'rabiul.alam@bracu.ac.bd', 'CSE'),
  ('HFN', 'Sheikh Araf Noshin', 'araf.noshin@bracu.ac.bd', 'CSE'),
  ('HMH', 'Mir Hamidul Hussain', 'hamidul.hussain@bracu.ac.bd', 'CSE'),
  ('IBA', 'Mr. Md. Imran Bin Azad', 'imran.azad@bracu.ac.bd', 'CSE'),
  ('IBU', 'Ms. Ipshita Bonhi Upoma', 'ipshita.upoma@bracu.ac.bd', 'CSE'),
  ('IRZA', 'Md. Irtiza Hossain', 'ext.irtiza.hossain@bracu.ac.bd', 'CSE'),
  ('KHR', 'Dr. Md. Khalilur Rahman', 'khalilur@bracu.ac.bd', 'CSE'),
  ('KKS', 'Md. Khaliduzzaman Khan Samrat', 'md.khaliduzzaman@bracu.ac.bd', 'CSE'),
  ('KNI', 'Ms. Khondoker Nazia Iqbal', 'nazia.iqbal@bracu.ac.bd', 'CSE'),
  ('KYK', 'Dr. Mohammad Kaykobad', 'kaykobad@bracu.ac.bd', 'CSE'),
  ('KZMN', 'Kazi Kamruzzaman Rabbi', 'kazi.kamruzzaman@bracu.ac.bd', 'CSE'),
  ('LBBH', 'Labib Hasan Khan', 'labib.hasan@bracu.ac.bd', 'CSE'),
  ('LMI', 'Lamiah Israt', 'lamiah.israt@bracu.ac.bd', 'CSE'),
  ('LRK', 'Lara khanom', 'lara.khanom@bracu.ac.bd', 'CSE'),
  ('MAF', 'MD ASIF', 'ext.md.asif@bracu.ac.bd', 'CSE'),
  ('MAFZ', 'Mehnaz Ara Fazal', 'ext.mehnaz.fazal@bracu.ac.bd', 'CSE'),
  ('MAHR', 'Mahrin Tasfe', 'mahrin.tasfe@bracu.ac.bd', 'CSE'),
  ('MAHS', 'Md Arif Hasan', 'arif.hasan@bracu.ac.bd', 'CSE'),
  ('MAJIJ', 'Majisha Jahan Disha', 'majisha.jahan@bracu.ac.bd', 'CSE'),
  ('MAO', 'Mirza Abdullah Al Noman', 'mirza.abdullah@bracu.ac.bd', 'CSE'),
  ('MAZW', 'Mirza Azwad Wakil', 'ext.azwad.wakil@bracu.ac.bd', 'CSE'),
  ('MDF', 'Mr. Mohammad Fahim', 'mohammad.fahim@bracu.ac.bd', 'CSE'),
  ('MHDE', 'Mehedi Hasan Emo', 'mehedi.emo@bracu.ac.bd', 'CSE'),
  ('MHSK', 'Maharin Mosfakin', 'ext.maharin.mosfakin@bracu.ac.bd', 'CSE'),
  ('MHY', 'Abu Musa Al Ashary', 'ext.abu.musa@bracu.ac.bd', 'CSE'),
  ('MNY', 'Dr. Muhammad Nur Yanhaona', 'nur.yanhaona@bracu.ac.bd', 'CSE'),
  ('MOM', 'Md. Moynul Asik Moni', 'moynul.moni@bracu.ac.bd', 'CSE'),
  ('MRIA', 'Ummay Maria Muna', 'maria.muna@bracu.ac.bd', 'CSE'),
  ('MSA', 'Dr. Matin Saad Abdullah', 'mabdullah@bracu.ac.bd', 'CSE'),
  ('MSAH', 'Dr. Md. Sakir Hossain', 'sakir.hossain@bracu.ac.bd', 'CSE'),
  ('MSMA', 'Mr. Md. Shamim Mia', 'shamim.mia@bracu.ac.bd', 'CSE'),
  ('MTOT', 'Md Toky Tazwar', 'ext.toky.tazwar@bracu.ac.bd', 'CSE'),
  ('MTSM', 'MD. MUHTASIM MAHMUD', 'muhtasim.mahmud@bracu.ac.bd', 'CSE'),
  ('MUNR', 'A B M Muntasir Rahman', 'abm.muntasir@bracu.ac.bd', 'CSE'),
  ('MVH', 'Mohammad Naveed Hossain', 'mohammad.naveed@bracu.ac.bd', 'CSE'),
  ('MZW', 'Maazin Munawar', 'ext.maazin.munawar@bracu.ac.bd', 'CSE'),
  ('NAFR', 'Md Nafiu Rahman', 'nafiu.rahman@bracu.ac.bd', 'CSE'),
  ('NAHC', 'Asif Hasan Chowdhury', 'asif.hasan@bracu.ac.bd', 'CSE'),
  ('NARC', 'Atonu Roy Chowdhury', 'atonuroy.chowdhury@bracu.ac.bd', 'CSE'),
  ('NAST', 'Nazmus Sakib Touhid', 'nazmus.touhid@bracu.ac.bd', 'CSE'),
  ('NBD', 'Dr. Badhan Das', 'badhan.das@bracu.ac.bd', 'CSE'),
  ('NDT', 'NIRJHOR DATTA', 'nirjhor.datta@bracu.ac.bd', 'CSE'),
  ('NFF', 'Nafiz Imtiaz Rafin', 'ext.nafiz.rafin@bracu.ac.bd', 'CSE'),
  ('NFMK', 'Md. Saif Mokarrom', 'saif.mokarrom@bracu.ac.bd', 'CSE'),
  ('NFS', 'Nafis Faisal', 'nafis.faisal@bracu.ac.bd', 'CSE'),
  ('NHBN', 'Hamim Ibne Nasim', 'hamim.nasim@bracu.ac.bd', 'CSE'),
  ('NKBS', 'Kefaya Benta Shahnoor', 'kefaya.shahnoor@bracu.ac.bd', 'CSE'),
  ('NKMA', 'K. M. Azwad Hossain', 'azwad.hossain@bracu.ac.bd', 'CSE'),
  ('NLAM', 'Namirul Islam', 'namirul.islam@bracu.ac.bd', 'CSE'),
  ('NLH', 'Niloy Farhan', 'niloy.farhan@bracu.ac.bd', 'CSE'),
  ('NMMR', 'MD MIZANUR RAHMAN MUSTAKIM', 'mizanur.mustakim@bracu.ac.bd', 'CSE'),
  ('NMP', 'Namira Mustafiz Pranty', 'ext.namira.pranty@bracu.ac.bd', 'CSE'),
  ('NNTN', 'Naima Tahsin Nodi', 'naima.tahsin@bracu.ac.bd', 'CSE'),
  ('NQM', 'Md Nafiz Ishtiaque Mahee', 'ext.nafiz.ishtiaque@bracu.ac.bd', 'CSE'),
  ('NRHB', 'Ruhan Habib', 'ruhan.habib@bracu.ac.bd', 'CSE'),
  ('NRT', 'Nusrat Zaman Raya', 'ext.nusrat.raya@bracu.ac.bd', 'CSE'),
  ('NRZR', 'Riazul Islam Rifat', 'riazul.islam@bracu.ac.bd', 'CSE'),
  ('NTR', 'Ms. Narzu Tarannum', 'narzu.tarannum@bracu.ac.bd', 'CSE'),
  ('NUR', 'Nur Mohammad Shaon', 'nur.shaon@bracu.ac.bd', 'CSE'),
  ('NWT', 'Nowshin Tabassum', 'ext.nowshin.tabassum@bracu.ac.bd', 'CSE'),
  ('NZRF', 'Niaz Ashraf Khan', 'niaz.ashraf@bracu.ac.bd', 'CSE'),
  ('NZU', 'Nazmul Islam', 'nazmul.islam1@bracu.ac.bd', 'CSE'),
  ('PBK', 'Mr. Partha Bhoumik', 'partha.bhoumik@bracu.ac.bd', 'CSE'),
  ('PDS', 'Mr. Purbayan Das', 'purbayan.das@bracu.ac.bd', 'CSE'),
  ('PLN', 'Pollock Nag', 'pollock.nag@bracu.ac.bd', 'CSE'),
  ('PRC', 'Pratick Roy Chowdhuruy', 'ext.pratick.roy@bracu.ac.bd', 'CSE'),
  ('QUZA', 'Quazi Ashikur Rahman', 'quazi.ashikur@bracu.ac.bd', 'CSE'),
  ('RAHA', 'Farzana Reefat Raha', 'reefat.raha@bracu.ac.bd', 'CSE'),
  ('RAK', 'Mr. Rubayat Ahmed Khan', 'rubayat.ahmed@bracu.ac.bd', 'CSE'),
  ('RAO', 'Mohammed Radoan', 'ext.mohammed.radoan@bracu.ac.bd', 'CSE'),
  ('RBR', 'Mr. Rakin Bin Rabbani', 'rakin.rabbani@bracu.ac.bd', 'CSE'),
  ('RDS', 'Rantu Das', 'ext.rantu.das@bracu.ac.bd', 'CSE'),
  ('RDW', 'Redowanul Akbar', 'redowanul.akbar@bracu.ac.bd', 'CSE'),
  ('RFF', 'Rafid Ahnaf', 'rafid.ahnaf@bracu.ac.bd', 'CSE'),
  ('RFR', 'Md. Rifat Rahman', 'rifat.rahman@bracu.ac.bd', 'CSE'),
  ('RFTS', 'Rifa Tasfiya', 'rifa.tasfiya@bracu.ac.bd', 'CSE'),
  ('RKBM', 'Mohammad Rakibul Hasan Mahin', 'mohammad.rakibul@bracu.ac.bd', 'CSE'),
  ('RKBR', 'Rakib Kibria', 'rakib.kibria@bracu.ac.bd', 'CSE'),
  ('RKN', 'Raisul Kabir News', 'raisul.kabir@bracu.ac.bd', 'CSE'),
  ('RRH', 'Mr. Rafeed Rahman', 'rahman.rafeed@bracu.ac.bd', 'CSE'),
  ('RSS', 'Rafiad Sadat Shahir', 'rafiad.shahir@bracu.ac.bd', 'CSE'),
  ('SADA', 'Sadif Ahmed', 'sadif.ahmed@bracu.ac.bd', 'CSE'),
  ('SADF', 'Saadat Rafid Ahmed', 'saadat.ahmed@bracu.ac.bd', 'CSE'),
  ('SAS', 'Dr. Md. Shafiul Alam Shuvo', 'ext.shafiul.shuvo@bracu.ac.bd', 'CSE'),
  ('SBB', 'Md. Sabbir Ahmed', 'sabbir.ahmed@bracu.ac.bd', 'CSE'),
  ('SBHN', 'Mr. Md Sabbir Hossain', 'sabbir.hossain@bracu.ac.bd', 'CSE'),
  ('SDAS', 'Sowmitra Das', 'sowmitra.das@bracu.ac.bd', 'CSE'),
  ('SDF', 'Dr. Md Sadek Ferdous', 'sadek.ferdous@bracu.ac.bd', 'CSE'),
  ('SDL', 'Shadmin Sultana', 'shadmin.sultana@bracu.ac.bd', 'CSE'),
  ('SDQ', 'Mr. Md. Saiful Bari Siddiqui', 'saiful.bari@bracu.ac.bd', 'CSE'),
  ('SDS', 'Mr. Shadman Shahriar', 'shadman.shahriar@bracu.ac.bd', 'CSE'),
  ('SEF', 'Sheikh Iftekhar Ahmed', 'ext.sheikh.ahmed@bracu.ac.bd', 'CSE'),
  ('SHBK', 'Sahib Kowsar', 'sahib.kowsar@bracu.ac.bd', 'CSE'),
  ('SHBZ', 'Dr. Md Shamsuzzoha Bayzid', 'ext.shams.bayzid@bracu.ac.bd', 'CSE'),
  ('SJM', 'Sajid Imam Mahir', 'ext.sajid.mahir@bracu.ac.bd', 'CSE'),
  ('SKIB', 'Nazmus Sakib Ahmed', 'nazmus.sakib@bracu.ac.bd', 'CSE'),
  ('SKZ', 'Dr. Sadia Hamid Kazi', 'skazi@bracu.ac.bd', 'CSE'),
  ('SMDS', 'Soumitra Das', 'ext.soumitra.das@bracu.ac.bd', 'CSE'),
  ('SMUR', 'Samiur Rahman', 'rahman.samiur@bracu.ac.bd', 'CSE'),
  ('SMYA', 'Sumaiya', 'sumaiya@bracu.ac.bd', 'CSE'),
  ('SOSB', 'Soumya Swagata Biswas', 'soumya.swagata@bracu.ac.bd', 'CSE'),
  ('SRJ', 'Ms. Mehnaz Seraj', 'seraj.mehnaz@bracu.ac.bd', 'CSE'),
  ('SRU', 'Mr. Shakir Rouf', 'shakir.rouf@bracu.ac.bd', 'CSE'),
  ('SSKD', 'Sheikh Samiul Kadir', 'ext.samiul.kadir@bracu.ac.bd', 'CSE'),
  ('STNM', 'Sanjida Tasnim', 'sanjida.tasnim@bracu.ac.bd', 'CSE'),
  ('SUE', 'Sukarna Sarker', 'sukarna.sarkar@bracu.ac.bd', 'CSE'),
  ('SWG', 'Mr. Swattic Ghose', 'swattic.ghose@bracu.ac.bd', 'CSE'),
  ('SWK', 'Dr. Swakkhar Shatabda', 'swakkhar.shatabda@bracu.ac.bd', 'CSE'),
  ('SZD', 'Md. Shazid Bin Mahbub', 'shazid.mahbub@bracu.ac.bd', 'CSE'),
  ('SZZ', 'Sazzadul Islam', 'sazzadul.islam@bracu.ac.bd', 'CSE'),
  ('TAP', 'Ms. Tasnim Ahsan Prome', 'tasnim.ahsan@bracu.ac.bd', 'CSE'),
  ('TAV', 'Tarvir Anjum Aditto', 'tarvir.anjum@bracu.ac.bd', 'CSE'),
  ('TAW', 'Mr. Md. Tawhid Anwar', 'tawhid.anwar@bracu.ac.bd', 'CSE'),
  ('THR', 'Tahsin Tanim Ramisha', 'ext.tahsin.ramisha@bracu.ac.bd', 'CSE'),
  ('TLQ', 'Dr. Taiabul Haque', 'taiabul.haque@bracu.ac.bd', 'CSE'),
  ('TMD', 'Mr. Tamkin Mahmud Tan', 'tamkin.mahmud@bracu.ac.bd', 'CSE'),
  ('TNF', 'Tanhiat Fatema Afnan', 'tanhiat.fatema@bracu.ac.bd', 'CSE'),
  ('TNMF', 'Ms. Tasnim Ferdous', 'tasnim.ferdous@bracu.ac.bd', 'CSE'),
  ('TRZ', 'Mr. Md. Tanzim Reza', 'tanzim.reza@bracu.ac.bd', 'CSE'),
  ('TSE', 'Tasneem Mazhar', 'tasneem.mazhar@bracu.ac.bd', 'CSE'),
  ('TSM', 'Mr. Mirza Md. Tanjim Shorif Mugdho', 'mirza.mugdho@bracu.ac.bd', 'CSE'),
  ('TVRR', 'Tanveer Rahman', 'tanveer.rahman@bracu.ac.bd', 'CSE'),
  ('TWK', 'Towshik Anam Taj', 'towshik.taj@bracu.ac.bd', 'CSE'),
  ('UJT', 'Umme Jannat Taposhi', 'jannat.taposhi@bracu.ac.bd', 'CSE'),
  ('UTKR', 'Utsha Kumar Roy', 'utsha.roy@bracu.ac.bd', 'CSE'),
  ('WBH', 'Waleed Bin Habib Khan', 'ext.waleed.bin@bracu.ac.bd', 'CSE'),
  ('WHMJ', 'Wahida Mahjabin', 'wahida.mahjabin@bracu.ac.bd', 'CSE'),
  ('WLV', 'Md.Waseq Alauddin Alvi', 'ext.waseq.alvi@bracu.ac.bd', 'CSE'),
  ('YND', 'Yasmin Nadia', 'yasmin.nadia@bracu.ac.bd', 'CSE'),
  ('ZAZ', 'Ihzaz Abrar Sadik', 'ihzaz.sadik@bracu.ac.bd', 'CSE'),
  ('ZBH', 'Md Zayed Bin Zahir Arju', 'zayed.zahir@bracu.ac.bd', 'CSE'),
  ('ZBYR', 'Zobayer Hasan', 'ext.zobayer.hasan@bracu.ac.bd', 'CSE'),
  ('ZHS', 'Mr. Syed Zamil Hasan Shoumo', 'shoumo.hasan@bracu.ac.bd', 'CSE'),
  ('ZLNM', 'Md. Zulkar Naim', 'zulkar.naim@bracu.ac.bd', 'CSE'),
  ('ZMD', 'Mr. Zaber Mohammad', 'zaber.mohammad@bracu.ac.bd', 'CSE'),
  ('ZYH', 'Zayed Humayun', 'zayed.humayun@bracu.ac.bd', 'CSE')
on conflict (initial) do nothing;
-- catalog-seed:faculties:end

commit;
