begin;

create table if not exists public.login_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  session_id uuid not null,
  signed_in_at timestamptz not null default now(),
  unique (user_id, session_id)
);

alter table public.login_events enable row level security;

revoke all on table public.login_events from anon, authenticated, public;

create or replace function public.record_login_event()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller uuid := auth.uid();
  current_session uuid;
begin
  if caller is null then
    raise exception 'Authentication required.';
  end if;

  current_session := nullif(auth.jwt() ->> 'session_id', '')::uuid;
  if current_session is null then
    raise exception 'Authenticated session identifier is missing.';
  end if;

  insert into public.login_events (user_id, session_id)
  values (caller, current_session)
  on conflict (user_id, session_id) do nothing;
end;
$$;

revoke all on function public.record_login_event() from public, anon, authenticated;
grant execute on function public.record_login_event() to authenticated;

create or replace view public.admin_account_login_metrics
with (security_invoker = true)
as
select
  profile.id as user_id,
  count(event.id) filter (
    where (event.signed_in_at at time zone 'Asia/Dhaka')::date =
      (now() at time zone 'Asia/Dhaka')::date
  )::bigint as daily_login_count,
  count(event.id) filter (
    where date_trunc('week', event.signed_in_at at time zone 'Asia/Dhaka') =
      date_trunc('week', now() at time zone 'Asia/Dhaka')
  )::bigint as weekly_login_count,
  count(event.id) filter (
    where date_trunc('month', event.signed_in_at at time zone 'Asia/Dhaka') =
      date_trunc('month', now() at time zone 'Asia/Dhaka')
  )::bigint as monthly_login_count,
  count(event.id)::bigint as total_login_count
from public.profiles profile
left join public.login_events event on event.user_id = profile.id
group by profile.id;

revoke all on table public.admin_account_login_metrics from anon, authenticated, public;
grant select on table public.login_events to service_role;
grant select on table public.admin_account_login_metrics to service_role;

notify pgrst, 'reload schema';

commit;
